### ISSUE TITLE
[Feature Request] Documentation for n_evaluations flag should be improved

### ISSUE THREAD

**Issue by justinkterry** [DLR-RM/rl-baselines3-zoo#100]
Right now, all that's said is:

`parser.add_argument("--n-evaluations", help="Number of evaluations for hyperparameter optimization", type=int, default=20)`

The problem is that this doesn't tell you what exact number is being referred to without diving into the code--it could plausibly be the number of times a hyperparameter set is evaluated and tested, the number of evaluation points during a training curve, or a few other things.

**Comment by araffin** [comment]
Hello,
I do agree on that point and would welcome a PR that clarifies its role ;)
