### ISSUE TITLE
Multiple concerns surrounding eval_freq

### ISSUE THREAD

**Issue by justinkterry** [DLR-RM/rl-baselines3-zoo#103]
1) The eval_freq passed to train.py as a command line arg is completely thrown out during optimization in favor one one generated from n_evaluations. This is either large omission in the command line argument description or a bug and I am not certain which. 
2) If that is not a bug, exp_mananger.py essentially has two different variables floating around named eval_freq, which makes tracking down what's going on very confusing. One should presumably be renamed or something.
3) This is a minor issue that I wouldn't have created an issue for on it's own, but the underscore in the variable name here https://github.com/DLR-RM/rl-baselines3-zoo/blob/8f41f40b24adf7c5ee3843f3ad4b5025d25b46f8/utils/exp_manager.py#L601 is not best style practices and I've stared at that line for a pretty long time now.

I'm also going to create a related issue in SB3.

**Comment by araffin** [comment]
>The eval_freq passed to train.py as a command line arg is completely thrown out during optimization in favor one one generated from n_evaluations. This is either large omission in the command line argument description or a bug and I am not certain which.

`eval_freq` is for normal training only.

For hyperparameter optimization, only `n_timesteps` and `n_evaluations` is used.

>If that is not a bug, exp_mananger.py essentially has two different variables floating around named eval_freq, which makes tracking down what's going on very confusing. One should presumably be renamed or something.

yep, the hyperparameter optimization can be rename to `optuna_eval_freq` or something similar with a comment to explain what it does.

>This is a minor issue that I wouldn't have created an issue for on it's own, but the underscore in the variable name here 

well, it was mostly to avoid overwriting `eval_freq` (I probably tried with both when creating the code).
