### ISSUE TITLE
SB3 v1.1 Breaking changes #116

### ISSUE THREAD

**Issue by justinkterry** [DLR-RM/rl-baselines3-zoo#104]
I recently upgraded to a SB3 1.1 prerelease (what's currently master), and the breaking changes have minor implications for RL zoo. I don't know if you want PRs for this now, for me to wait until 1.1 is properly released, or if you want to do the upgrade yourself what. So far I've found one problem I've had to fix on my fork though:

```
Traceback (most recent call last):
  File "train.py", line 15, in <module>
    from utils.exp_manager import ExperimentManager
  File "/home/justin_terry/rl-baselines3-zoo/utils/exp_manager.py", line 26, in <module>
    from stable_baselines3.common.vec_env.obs_dict_wrapper import ObsDictWrapper
ModuleNotFoundError: No module named 'stable_baselines3.common.vec_env.obs_dict_wrapper'
```

**Comment by araffin** [comment]
>So far I've found one problem I've had to fix on my fork though:

I'm not sure what you mean. The master version of the zoo is to be used with the master version of SB3 (cf requirements.txt).

And this breaking change is documented: https://stable-baselines3.readthedocs.io/en/master/misc/changelog.html#breaking-changes

**Comment by justinkterry** [comment]
I somehow managed to miss the commit master adding 1.1 support, my apologies.
