### ISSUE TITLE
[Question] the proof that PyBullet's environment is more difficult than Mujoco's environment

### ISSUE THREAD

**Issue by my87432122** [DLR-RM/rl-baselines3-zoo#111]
Hi, I saw this description in the `README.md`
```
Note: those environments are derived from Roboschool and are harder than the Mujoco version (see Pybullet issue) 
```
But when I clicked on the link about Pybullet issue, I found that the issue is no longer valid.

Therefore, I would like to ask if there are other links that can prove that the PyBullet environment is more complicated than MuJoCo?

**Comment by araffin** [comment]
>But when I clicked on the link about Pybullet issue, I found that the issue is no longer valid.

Oh I see, all issues were removed/moved.
You can find an archived version [here](http://web.archive.org/web/20210607101005/https://github.com/bulletphysics/bullet3/issues/1718).

Basically, the robots used are heavier which prevent some weird behavior observed on Mujoco ones:
- the half cheetah cannot flip around
- the walker must walk (and cannot run as it is the case in the Mujoco version)

I think that the reward function are also different but apart from looking at the code, I don't have much reference to give you.

**Comment by my87432122** [comment]
Ok, I got it. Thanks!
