### ISSUE TITLE
[Feature Request] Logging Policy During Optimization

### ISSUE THREAD

**Issue by justinkterry** [DLR-RM/rl-baselines3-zoo#113]
So I'm using RL Zoo because I need to find optimal policies for a bunch of different rl environments for my research. It would save me an extra step if, during hyperparameter tuning, the policies and evaluation logs were saved. That way I could just pull optimal policies from the rl zoo training process instead of retraining with good hyperparameters.

1) Would you be open to a PR for this?
2) Do you have an idea for a reasonable system to save logs and policies for each run without overwriting them on one machine? My guess is `./logs/+<trial number>+/`?

**Comment by justinkterry** [comment]
3. If you do want to go with `./logs/+<trial number>+/`, do you know what the non-hacky way to pass the optuna trial number to the objective function is?

**Comment by araffin** [comment]
>Would you be open to a PR for this?

Sounds like a reasonable feature (but should be deactivated by default as it takes quite some space).

>Do you have an idea for a reasonable system to save logs and policies for each run without overwriting them on one machine? My guess is ./logs/+<trial number>+/?

something like `logs/<algorithm>/study-<env id>-<unique-id-for-the-study>/<trial number>/` ?

>o you know what the non-hacky way to pass the optuna trial number to the objective function is?

You can probably access it from the trial object, no?

https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/utils/exp_manager.py#L577
