### ISSUE TITLE
[Proposal] Script for handling best hyperparameters

### ISSUE THREAD

**Issue by jkterry1** [DLR-RM/rl-baselines3-zoo#114]
In my own fork I have a script that parses through optuna logs after a hyperparameter tuning run. You can use it to print the dictionaries for the `n` best hyperparameters or save them to .json files, list the best final average rewards found in order and so on. This functionality seems worth contributing upstream. Do you agree, and if so how would you like it included?

**Comment by araffin** [comment]
>Do you agree, and if so how would you like it included?

It seems like a good addition, but it may already be included in Optuna, no?

Recently, I'm also saving the study object (and not only csv, which allow for instance to use Optuna visualizing tools): https://github.com/DLR-RM/rl-baselines3-zoo/pull/106

**Comment by justinkterry** [comment]
I don't believe optuna has a feature to give you the n best hyperparameters without parsing throigh database outputs after looking through the documentation again.

**Comment by araffin** [comment]
>I don't believe optuna has a feature to give you the n best hyperparameters without parsing throigh database outputs after looking through the documentation again.

After checking, you are right, it does not seem to be included yet.

If I understand it correctly, the script consist of a bunch of pandas commands to sort and display the best hyperparams, no?

**Comment by justinkterry** [comment]
I doesn't use pandas, but basically yes. It:

- Lets you print rewards from highest to lowest (which is something I use a lot at least and is not built into optuna)
- Lets you print (or save to json) the hyperparameter dicts the hyperparameters for the n best trials

**Comment by araffin** [comment]
Ok, then please do a PR and we will discuss the details there ;)

**Comment by jkterry1** [comment]
Closing in favor of my PR
