### ISSUE TITLE
[Bug] lr instead of learning_rate as optuna parameter key in hyperparams_opt.py

### ISSUE THREAD

**Issue by justinkterry** [DLR-RM/rl-baselines3-zoo#115]
Right now, you have a bunch of lines like this in hyperparams_opt.py:

`learning_rate = trial.suggest_loguniform("lr", 1e-5, 1)`

The problem with this is that it makes the dictionary key for optuna `lr` instead of `learning_rate`, which isn't an argument for any SB3 learning method (while all other optuna parameter dict keys are). Because of this so the dictionary can't be directly passed to a learning method later without modification. This came up for me when I was training the best 16 hyperparameters 10 times to find the set thats /actually/ the best/.

**Comment by justinkterry** [comment]
I have a branch with this fixed here: https://github.com/PettingZoo-Team/rl-baselines3-zoo

**Comment by araffin** [comment]
>Because of this so the dictionary can't be directly passed to a learning method later without modification.

In fact, that's the case for different hyperparameters (for instance the network architecture) but a script that yield the yaml config that can be copy-pasted directly would be definitely helpful (this would require some if/else but should be doable).

**Comment by justinkterry** [comment]
I mean this would at least make the parameters searched by default copiable. Also, at a bare minimum this is the only place in the entire code where it's referred to as "lr" not "learning_rate," which constitutes a minor style issue. Do you object to a PR?

**Comment by araffin** [comment]
>Do you object to a PR?

I do agree for a PR but I would even go one step further to makes things simpler to copy paste ;)
