### ISSUE TITLE
FetchPush tqc or her?

### ISSUE THREAD

**Issue by hskAlena** [DLR-RM/rl-baselines3-zoo#125]
Hi! I'm new to rl-baselines3-zoo. 
I want to try out FetchPush-v1 with TQC or HER, but I couldn't download trained agents of TQC with 'git clone --recursive'.
And I found out HER is deprecated now(I guess?), so I couldn't _'enjoy'_ FetchPush-v1 with trained agents of HER.
(I got an error message that HER is not in possible algo choices.)

So I tried to train TQC myself
`python train.py --algo tqc --env FetchPush-v1`
, but error occurs with the message below.

`Traceback (most recent call last):
  File "train.py", line 174, in <module>
    model = exp_manager.setup_experiment()
  File "/home/name/projects/rl-baselines3-zoo/utils/exp_manager.py", line 171, in setup_experiment
    **self._hyperparams,
TypeError: __init__() got an unexpected keyword argument 'replay_buffer_class'
`

Am I doing something wrong? How can I fix it?

**System Info**
I forgot how I installed Stable Baselines3, but either pip or source.
Python version is 3.7.9
pytorch version is 1.7.1

**Comment by araffin** [comment]
Hello,

>I want to try out FetchPush-v1 with TQC or HER, but I couldn't download trained agents of TQC with 'git clone --recursive'

yes, I need to retrain the models, will try to do that soon (before the v1.1.0 release).

> , but error occurs with the message below.
> I forgot how I installed Stable Baselines3, but either pip or source.

This is your error, please follow the instructions of the README and do `pip install -e requirements.txt`, it should fix your issue ;)

**Comment by hskAlena** [comment]
Thanks! It worked with the command 
`pip install -r requirements.txt`
