### ISSUE TITLE
[question] How to set max step for SAC

### ISSUE THREAD

**Issue by ZY-KK** [DLR-RM/rl-baselines3-zoo#132]
Hi,  I have question about reset.
When I run SAC  algorithm by using this, the reset only happen if the task is done. But sometime, the robot move wrongly, so I would like to know if I can add some parameters to set the max steps, once the step greater than maximum, it will reset.
Thank you!

**Comment by Miffyli** [comment]
You could use the [TimeLimitWrapper](https://github.com/openai/gym/blob/master/gym/wrappers/time_limit.py) from original gym and apply it on your environment. @araffin This could probably be a nice config parameter?

**Comment by araffin** [comment]
> You could use the [TimeLimitWrapper](https://github.com/openai/gym/blob/master/gym/wrappers/time_limit.py) from original gym and apply it on your environment. @araffin This could probably be a nice config parameter?

yes and this is already possible to add the wrapper in the config file (cf README)

**Comment by araffin** [comment]
An example: https://github.com/DLR-RM/rl-baselines3-zoo/blob/feat/offline-RL/hyperparams/tqc.yml#L146

**Comment by ZY-KK** [comment]
Thank you so much!
