### ISSUE TITLE
[question] make_atari_env() is not used for Atari environments 

### ISSUE THREAD

**Issue by rienath** [DLR-RM/rl-baselines3-zoo#133]
## Question
Why does the zoo call standard `make_vec_env()` for all environments, including Atari, when sb3 has a special function for it `make_atari_env()`?

## Train of thought
- train.py calls [exp_manager.setup_experiment()](https://github.com/DLR-RM/rl-baselines3-zoo/blob/96f1a59b407f49a9beccbb1c6948fa502a4717d5/train.py#L185) to `# Prepare experiment and launch hyperparameter optimization if needed`
- which calls [self.create_envs()](https://github.com/DLR-RM/rl-baselines3-zoo/blob/96f1a59b407f49a9beccbb1c6948fa502a4717d5/utils/exp_manager.py#L160)
- which calls [make_vec_env()](https://github.com/DLR-RM/rl-baselines3-zoo/blob/96f1a59b407f49a9beccbb1c6948fa502a4717d5/utils/exp_manager.py#L496) from stable_baselines3
- it calls `make_vec_enc()`, even when the environment is Atari, but could call [make_atari_env()](https://github.com/DLR-RM/stable-baselines3/blob/2fa06ae8d24662a40a7c247dd96625bebf182dce/stable_baselines3/common/env_util.py#L108)

**Comment by araffin** [comment]
Hello,
mostly to keep the same interface in the zoo, be more transparent and allow the user to do other kind of pre-processing (this also allow to disable part of the atari wrappers if needed).

In practice, it is equivalent as the wrapper is manually specified in the config file.

See A2C params for instance: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/a2c.yml#L3

**Comment by rienath** [comment]
Hello, thanks for a speedy reply! It makes sense now.

I think of exposing gym audio to be able to train agents with both audio and video produced by the Atari environments. It is similar to what @Miffyli did with VizDoom in [that](https://arxiv.org//1905.04192.pdf) paper. I thought it would be better to do it using zoo/sb3 as it would allow others to train on audio and video too, but I am quite puzzled when I look at the code now. 

Although it is not a 100% commitment, do you have any suggestions, cautions or tips on the matter? Maybe someone else tried it before me?

**Comment by Miffyli** [comment]
@rienath 

Oh no somebody spotted the paper :') (btw you might interested in [this one as well](https://sites.google.com/view/sound-rl), we will add the arxiv link tomorrow).

I recommend you steer away from zoo for now and focus on only using SB3 for now. I do not know other ways of getting audio from Atari other than [Gym Retro](https://github.com/openai/retro) (I am not 100% sure if they have Atari games). However things should be pretty easy once you have the audio by making a Dict observation space, where one input is the image and another is the audio.

**Comment by rienath** [comment]
@Miffyli 

Sorry for the late reply. Wanted to get as stuck as possible before contacting you. Cheers for the link, both your papers are really interesting. The 2019 one was actually my main reference for a scholarship I have received, so it is quite a coincidence that we met here! And thank you for co-writing it! 😂

Here is a link to my code:
https://github.com/rienath/stable-baselines3/tree/gym-to-retro

## What I have done

Indeed, Gym Retro allows to get audio and supports Atari games, however, unlike the conventional gym, it does not have different extensions like v4, v0, ram, NoFrameskip, and so on. So 
That is why I have added the [make_retro_env()](https://github.com/rienath/stable-baselines3/blob/00c63735b9242b1e4cd380046aca84863fa102c7/stable_baselines3/common/env_util.py#L164) that will parse the normal gym-like environment names and appropriately wrap the environment to make it work. I promise I will make a proper RetroWrapper and make it neat when I am finished!

I have not used 2 wrappers that are there for standard Gym Atari:
- NoopResetEnv, as it consistently gave worse results on DQN and PPO with Breakout.
- EpisodicLifeEnv, because I have not found a way to get information on lives from Retro.

## Questions
* Afaik, sandard v0 and v4 environments have a frameskip of 2-4. A random number between these values is chosen at every step for a frameskip. [The wrapper](https://github.com/DLR-RM/stable-baselines3/blob/2fa06ae8d24662a40a7c247dd96625bebf182dce/stable_baselines3/common/atari_wrappers.py#L114) that tries to achieve that for gym Atari is MaxAndSkipEnv, but it only accepts a single value. 
Also, doesn't the standard gym take care of frameskip and repeat_action_probability? If it does, then why are we using MaxAndSkipEnv, if it does not, don't we make `BreakoutNoFrameskip-v0` a `BreakoutDeterministic-v4` by having a frameskip 4 and no repeat_action_probability variable?

![](https://user-images.githubusercontent.com/30183178/125300356-d9a7a280-e321-11eb-82bc-c831fd348974.png)

* Getting the audio out of gym retro is trivial `em.get_audio()`. I will apply FFT, however, before adding it to observations (especially after reading your new paper). However, I am not exactly sure where I should be modifying the observation space as you suggested. Also, I am not sure where to actually add the audio to observations.
* [Why do we make another action after firing](https://github.com/DLR-RM/stable-baselines3/blob/2fa06ae8d24662a40a7c247dd96625bebf182dce/stable_baselines3/common/atari_wrappers.py#L63) in FireResetEnv? 

## How to run
If you want to run my code, just insert this into Colab:
```
!pip install -q gym
!pip install -q gym-retro
!git clone -b gym-to-retro https://github.com/rienath/stable-baselines3.git
!wget http://www.atarimania.com/roms/Roms.rar && unrar x Roms.rar && unzip ROMS.zip
!python -m retro.import ROMS/
!python -m atari_py.import_roms ROMS/
!mv stable-baselines3/stable_baselines3 stable_baselines3
!apt install xvfb -y
!pip install pyvirtualdisplay
!pip install piglet

from pyvirtualdisplay import Display
display = Display(visible=0, size=(1400, 900))
display.start()

import stable_baselines3
from stable_baselines3.ppo import PPO
from stable_baselines3.common.env_util import make_retro_env

env = make_retro_env('BreakoutDeterministic-v4', seed=0)
model = PPO("CnnPolicy", env, verbose=0, tensorboard_log="./PPO/")

%load_ext tensorboard
%tensorboard --logdir ./PPO/
```
and in a separate cell:
```model.learn(total_timesteps=1000000)
env.close()

**Comment by Miffyli** [comment]
Amazing work! The code is pretty clean and exhaustive on a quick glimpse :). Not to undermine your work, but tbh I am not 100% sure how much the "-v1" and other non-zero envs are used, as the same effects can be added manually with wrappers like done here., but it is nice to have for completeness!

> Afaik, standard v0 and v4 environments have a frameskip of 2-4.

MaxAndSkipEnv wrappers takes max over the skipped frames which makes sure all entities that were drawn during the skipped frames will be shown (some entities in Atari games might "blink" on and off between frames because of rendering limitations, and frameskipping at correct rate could render them always invisible). But yes, Gym handles the other things (e.g. action repetition)

> I will apply FFT, however, before adding it to observations (especially after reading your new paper). However, I am not exactly sure where I should be modifying the observation space as you suggested. Also, I am not sure where to actually add the audio to observations.

To reduce compute overhead and stuff, you could return an observation dict with the image and audio (e.g. keys `image` and `audio`). Then you could make a wrapper that turns audio (samples) into FFT vector much we like described in the paper. This way you do not need to store as much data (the FFT vector is subsampled and is smaller in size than the original audio).

> Why two actions
That's a good question. I first thought it was to make sure the ball appears (maybe it does not appear immediately after "UP"?"), but that does not seem to be case on quick testing. This code is straight from [OpenAI Baselines](https://github.com/openai/baselines/blob/ea25b9e8b234e6ee1bca43083f8f3cf974143998/baselines/common/atari_wrappers.py#L41).

**Comment by hegde95** [comment]
@rienath This looks interesting, a good wrapper for sound for gym_retro will make life easy. As @Miffyli mentioned, [This](https://github.com/hegde95/Agents_that_Listen/blob/main/envs/doom/wrappers/sound_wrapper.py)  kind of wrapper may help you add the sound as a vector. You may use torch's FFT transform (like [here](https://github.com/hegde95/Agents_that_Listen/blob/main/envs/doom/doom_model.py#L160)), but since this is a tensor operation might be a good idea to not keep it in this wrapper.

**Comment by rienath** [comment]
@Miffyli, thank you for taking the time to give an elaborate reply and encouraging me. :)

[The link to my code is the same](https://github.com/rienath/stable-baselines3/tree/gym-to-retro).

> you could return an observation dict with the image and audio

I have implemented a [RetroSound wrapper](https://github.com/rienath/stable-baselines3/blob/e8c49304873327b8a4f03401649e24681572c088/stable_baselines3/common/atari_wrappers.py#L310) (@hegde95 DoomSound was a reference, very helpful!) that gets raw audio exactly how you described it. I have also changed the implementation of StocahsticFrameskip, the wrapper I have written to manage the frameskip. If we use audio and are skipping frames, we need to save the audio for skipped frames too for training, so StochasticFramskip has a buffer that will save and return this audio. 

The length of the sound signal in the observation space dictionary will be `length of momentary audio * frames skipped`.
When we have a varying frameskip 2-4 observation space will have the longest possible signal, `length of momentary audio * 4` in this case, and when the frameskip drops below the maximum value, the remaining part of the array will be padded with  0's.

The FPS drops by about 12% when training on video and raw audio. 
Here is what the mean episode reward looks like on a single seed with `BreakoutDeterministic-v4`.
* The orange line: PPO, MultiInputPolicy, video + raw audio.
* The blue line: PPO, CnnPolicy, video.

![image](https://user-images.githubusercontent.com/30183178/126797205-966ac64f-b840-408d-b4e5-853cca445599.png)

> Then you could make a wrapper that turns audio (samples) into FFT vector much we like described in the paper.

> You may use torch's FFT transform (like here), but since this is a tensor operation might be a good idea to not keep it in this wrapper.

This is what I am planning to do next: make a dedicated wrapper to put on top of the RetroSound that will transfer raw audio to FFT features, however, I am not sure whether it is correct to have a tensor operation in a wrapper whatsoever. Do you know whether that is ok or there is a better way to do it? 

## How to run (updated)
If you want to run my code, just insert this into Colab:

```
!pip install -q gym
!pip install -q gym-retro
!git clone -b gym-to-retro https://github.com/rienath/stable-baselines3.git

!wget http://www.atarimania.com/roms/Roms.rar && unrar x Roms.rar && unzip ROMS.zip
!python -m retro.import ROMS/
!python -m atari_py.import_roms ROMS/
!mv stable-baselines3/stable_baselines3 stable_baselines3
!rm -rf stable-baselines3/

!apt install xvfb -y
!pip install pyvirtualdisplay
!pip install piglet

from pyvirtualdisplay import Display
display = Display(visible=0, size=(1400, 900))
display.start()

import stable_baselines3
from stable_baselines3.ppo import PPO
from stable_baselines3.common.env_util import make_retro_env

env = make_retro_env('BreakoutDeterministic-v4', seed=0, fire_at_start=True, audio=True)
model = PPO("MultiInputPolicy", env, verbose=0, tensorboard_log="./AUDIO_TEST/")

%load_ext tensorboard
%tensorboard --logdir ./AUDIO_TEST/
```

and in a separate cell:
```
model.learn(total_timesteps=1000000)
env.close()
```

**Comment by Miffyli** [comment]
Happy to help when somebody puts in the time to share things in such a detailed manner :)

> I have implemented a RetroSound wrapper ...

This sounds good and I do not see any bigger flaws in this setup.

> Here is what the mean episode reward looks like on a single seed with BreakoutDeterministic-v4.

I am not sure what was the expectation (higher reward for audio-enabled agent?), but I am not surprised the results still are the same: if you are feeding audio samples as-is to a fully-connected network (default in MultiInputPolicy for 1D inputs), it will have very hard time distinguishing anything. It is also not certain if audio-input provides any help in Breakout.

I recommend you setup a quick sanity-check environment where optimal agent _has_ to process the audio in a sensible manner to complete the task, and once that checks out, run Atari experiments.

> This is what I am planning to do next: make a dedicated wrapper to put on top of the RetroSound that will transfer raw audio to FFT features, however, I am not sure whether it is correct to have a tensor operation in a wrapper whatsoever. Do you know whether that is ok or there is a better way to do it?

It is probably easiest to do with a wrapper, as you suggested, using `np.fft.fft` function. Something along lines of

```python
import numpy as np
audio = np.random.random((100,))
# Apply windowing on audio. Otherwise you will have very odd frequency artifacts
audio = np.hamming(100) * audio
fourier = np.fft.fft(audio)
# Take only the magnitudes of different frequencies
magnitudes = np.abs(fourier)
# First element is sum of audio, which is overly large and normalizing might be difficult
# Last half of the magnitude are mirror of first half (see Nuqyist frequency)
magnitudes = magnitudes[1:(100 // 2) + 1]
# Take logarithm, as these magnitudes may be very large, and networks do not enjoy large values
log_magnitudes = np.log(magnitudes + 1e-5)
```
The `log_magnitudes` vector would be the FFT input for your agents. The same is done [here](https://github.com/hegde95/Agents_that_Listen/blob/main/envs/doom/doom_model.py#L199), but in PyTorch with more obscure functions (more up-to-date PyTorch versions also have more convenient FFT function). 

If the "windowing" and Nuqyist frequency concepts are new to you, I highly recommend reading up on signal processing :). If you are going to work on RL agents + audio, these concepts will continue to creep up (and many others as well).

**Comment by rienath** [comment]
I have implemented FFTWrapper with tweaked code that you have provided, @Miffyli. 
> I am not sure what was the expectation (higher reward for audio-enabled agent?)

It was within my expectations, but here is what I did not expect:

![image](https://user-images.githubusercontent.com/30183178/127384056-d439d76f-69f3-4c66-8030-91063da43979.png)

The orange line is video and the green line is fft audio + video. I am not exactly sure how to interpret this. I understand why raw audio did not have any effect, but I am puzzled as fft seems to reduce the reward. Maybe it is because I have tested it on 1 seed or with a little number of steps, and it learns slower as there is more useful data to learn from.

> It is also not certain if audio-input provides any help in Breakout.

My research focuses on games where audio exists and provides some information about the environment (maybe the same information as the image, in Breakout, for example, you can see when the ball hits the walls/blocks and you can also hear it), but it is not certain whether audio input is helpful or not. That is why I usually do tests on Breakout.

> I recommend you setup a quick sanity-check environment where optimal agent has to process the audio in a sensible manner to complete the task.

That would be amazing, but I am limited to retro ROMs and I do not know whether there is such a game on Atari or the rest of the retro consoles. Let me know if you've heard of any! 

Also, your paper states that after performing fft you `downsample with a 1D max-pool layer and then feed it through a two-layer, fully connected network. This discards the temporal information inside the 114ms of audio, but enables robust performance and a simple network architecture.`
Tbh, I did not entirely understand that part of the paper. I assumed it reduces the number of features? If so, is it sensible to do something similar in my implementation too?

**Comment by Miffyli** [comment]
> Maybe it is because I have tested it on 1 seed or with a little number of steps, and it learns slower as there is more useful data to learn from.

Indeed not promising, but I would not draw conclusions before, say, at least three repetitions and preferably with more training time (say, 10M steps). I know this can be computationally very expensive for you and takes long, but sadly that is how DRL works :( . You can not avoid this part, and trying to draw conclusions from insufficient data may mislead you big time.

> My research focuses on games where audio exists and provides some information about the environment (maybe the same information as the image, in Breakout, for example, you can see when the ball hits the walls/blocks and you can also hear it), but it is not certain whether audio input is helpful or not. That is why I usually do tests on Breakout.

This information would be nice to see with exhaustive experiments indeed! It is hard to say if it generally will be helpful or just "confuse" the network information that is not helpful ^^

> That would be amazing, but I am limited to retro ROMs and I do not know whether there is such a game on Atari or the rest of the retro consoles. Let me know if you've heard of any!

If you are using SB3/SB3-zoo, you can easily change the environment and do not have to be stuck with simple environments. I recommend you create a simple toy-environment solely designed to test if the audio-input part works (see [example of an example toy-env for multi-input policies](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/envs/multi_input_envs.py)). It should be something which you can not solve with image/main observation alone, and you "need" to process the audio stuff correctly. 

To mimic the vizdoom paper, this could be a simple 2D gridworld environment with two potential goals, picked at random on each episode. Agent receives a sine wave with frequency propotional to distance to the _correct_ goal. Without audio info it will learn to pick goals at random (or always pick one) -> 0.5 average completion rate. With sound info it should learn to go correct goal all the time.

**Comment by rienath** [comment]
@Miffyli 
First of all, I have adapted the _EpisodicLifeEnv_ wrapper to work both with gym and retro. I have also ~~made~~ found a wrapper that allows to keep only required discrete actions and their combos reducing the action space. So retro is currently very similar to gym, the only major difference being lack of NoopResetEnv wrapper, which can easily be added, but gives worse results when I use it, and I do not understand why theoretically we would need to have no actions for n steps at the beginning of episode anyway.

> If you are using SB3/SB3-zoo, you can easily change the environment and do not have to be stuck with simple environments.

Indeed, thanks for the link. I have looked deeper into this and made the environment that you have described. The game made has a 1D map.
```
 ___________________________
| 0  1  2  3  4  5  6  7  8 |
 ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
```
We start the game at a random position [2-6]. We can move left or right, we get a negative reward of -0.025 on each step. The correct goal is either 0 or 8, which will give us a reward of 1. If we reach the wrong goal, we will get a reward -1 and the game will finish. The closer we are to the goal, the higher is the frequency of sin wave.

The orange line is image+raw audio.
The red line is just the image.
The blue line is image + FFT audio. It uses both RetroSound and FFTWrapper wrappers. I have simulated env.em.get_audio() function and did not give raw audio straight out of the environment in this experiment, unlike in the orange line one, to see how it goes through the entire audio acquisition (implemented in RetroSound) and processing (implemented in FFTWrapper). 

![image](https://user-images.githubusercontent.com/30183178/128080616-0549d6f0-68fe-4e8a-9a70-1148b2c8ec8b.png)

It works! 🥳

> Indeed not promising, but I would not draw conclusions before, say, at least three repetitions and preferably with more training time (say, 10M steps).

I did not want to do it back then because the code was not finished, but I might as well do it next as I think I am done and the project is coming to the end.

> It is hard to say if it generally will be helpful or just "confuse" the network information that is not helpful ^^

This is exactly what I am trying to find out! We have talked quite a lot here and I would have been stuck a long time ago without you! Thank you again and could I contact you more privately? 

# Code
This is my code for the 1D environment in case anyone ever needs it.

```
from typing import Dict, Union
import gym
import numpy as np
import stable_baselines3
from stable_baselines3.ppo import PPO
from stable_baselines3.common.atari_wrappers import RetroSound, FFTWrapper
from stable_baselines3.common.type_aliases import GymStepReturn

class emulator():
    """
    This class models retro emulator that can return audio to make env.em.get_audio() possible in the wrappers.
    """
    def __init__(self, audio):
        self.audio = audio

    def get_audio(self):
        return self.audio
    
    def update_audio(self, audio):
        self.audio = audio 


class AudioMultiObsEnv(gym.Env):
    """
    GridWorld-based MultiObs Environments 1x8.
        ___________________________
       | 0  1  2  3  4  5  6  7  8 |
       ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
    start is 4 or random
    goal is 0 or 8, randomly determined in every round
    if we reach incorrect goal, we get punished (reward -1)
    if we reach correct goal, we get rewarded (reward -1)
    actions are = [left, right]
    each state is represented by a random image
    each state has stereo audio; the closer state is to goal, the higher the frequency
    each step has a punishment (reward -0.025)
    :param num_col: Number of columns in the grid
    :param random_start: If true, agent starts in random position apart from the goal/false-goal positions and states directly next to them
    """

    def __init__(
        self,
        num_col: int = 9,
        random_start: bool = True,
        return_audio: bool = False
    ):
        super(AudioMultiObsEnv, self).__init__()

        self.img_size = [84, 84, 1]

        self.random_start = random_start
        self.action_space = gym.spaces.Discrete(2)

        self.observation_space = gym.spaces.Dict(
            spaces={
                "obs": gym.spaces.Box(0, 255, self.img_size, dtype=np.uint8),
            }
        )

        self.return_audio = return_audio
        self.count = 0
        self.max_count = 20 # Number of maximum steps
        self.log = ""
        self.state = 4
        self.action2str = ["left", "right"]
        self.init_possible_transitions()
        self.num_col = num_col
        self.state_mapping = []
        self.sounds = []
        self.init_state_mapping()
        self.min_state = 0
        self.max_state = num_col - 1
        self.win_state = np.random.choice([self.min_state, self.max_state])
        self.update_state_mapping()
        self.em = emulator(self.get_state_mapping()["audio"]) # Makes env.em.get_audio possible for wrappers

    def init_state_mapping(self) -> None:
        """
        Initializes the state_mapping array which holds the observation values for each state
        """

        # Each state is represented by a random image
        col_imgs = np.random.randint(0, 255, (self.num_col, 84, 84), dtype=np.int32)

        # Each state is represented by sin wave of a certain frequency. The closer the state is to the goal
        # the higher the frequency.
        for i in range(self.num_col):
            # Get x values of the sin wave
            time = np.arange(0, 524, 1)
            frequency = i*100
            # Amplitude of the sine wave is sine of freauency * time
            amplitude = np.sin(frequency*time)
            # Get the amplitude to format [[l, r], [l, r]...] and so on as this is the representation
            # of stereo audio in retro.
            stereo_waves = np.transpose([amplitude, amplitude])
            self.sounds.append(stereo_waves)
        
        # Arrange sounds as if goal is the last state by default
        for i in range(self.num_col):
            self.state_mapping.append({"obs":   col_imgs[i].reshape(self.img_size),
                                       "audio": self.sounds[i]})
    
    def update_state_mapping(self):
        if self.win_state == self.min_state:
            for i in range(self.num_col):
                self.state_mapping[i]["audio"] = self.sounds[i]
        else:
            sounds_reversed = self.sounds[::-1]
            for i in range(self.num_col):
                self.state_mapping[i]["audio"] = sounds_reversed[i]

    def get_state_mapping(self) -> Dict[str, np.ndarray]:
        """
        Uses the state to get the observation mapping.
        :return: observation dict
        """
        return self.state_mapping[self.state]

    def init_possible_transitions(self) -> None:
        """
        Initializes the transitions of the environment.
        """
        self.left_possible = [1, 2, 3, 4, 5, 6, 7, 8]
        self.right_possible = [0, 1, 2, 3, 4, 5, 6, 7]
        self.down_possible = []
        self.up_possible = []

    def step(self, action: Union[int, float, np.ndarray]) -> GymStepReturn:
        """
        Run one timestep of the environment's dynamics. When end of
        episode is reached, you are responsible for calling `reset()`
        to reset this environment's state.
        Accepts an action and returns a tuple (observation, reward, done, info).
        :param action:
        :return: tuple (observation, reward, done, info).
        """
        action = int(action)

        self.count += 1

        prev_state = self.state

        reward = -0.025
        # Define state transition
        if self.state in self.left_possible and action == 0:  # left
            self.state -= 1
        elif self.state in self.right_possible and action == 1:  # right
            self.state += 1

        got_to_end = self.state == self.max_state or self.state == self.min_state
        if got_to_end:
            reward = 1 if self.state == self.win_state else -1
        done = self.count > self.max_count or got_to_end

        self.log = f"Went {self.action2str[action]} in state {prev_state}, got to state {self.state}"

        # Update audio in emulator
        self.em.update_audio(self.get_state_mapping()["audio"])

        if self.return_audio:
            return self.get_state_mapping(), reward, done, {"got_to_end": got_to_end}
        else:
            return {"obs": self.get_state_mapping()["obs"]}, reward, done, {"got_to_end": got_to_end}

    def render(self, mode: str = "human") -> None:
        """
        Prints the log of the environment.
        :param mode:
        """
        print(self.log)

    def reset(self) -> Dict[str, np.ndarray]:
        """
        Resets the environment state and step count and returns reset observation.
        """
        self.count = 0
        self.win_state = np.random.choice([self.min_state, self.max_state])
        # Update frequencies of states as the goal might have changed.
        self.update_state_mapping()
        if not self.random_start:
            self.state = 4
        else:
            self.state = np.random.randint(2, self.max_state - 2)
        # Update audio in emulator
        self.em.update_audio(self.get_state_mapping()["audio"])
        if self.return_audio:
            return self.get_state_mapping()
        else:
            return {"obs": self.get_state_mapping()["obs"]}
```

**Comment by Miffyli** [comment]
> NoopResetEnv wrapper, which can easily be added, but gives worse results when I use it, and I do not understand why theoretically we would need to have no actions for n steps at the beginning of episode anyway.

This is to add stochasticity to Atari environments. By default they are deterministic, so the agent could learn to do very simple "repeat this sequence of actions" type of things. By starting the environment in _slightly_ different initial states, the agent has to learn to be a touch more dynamic :)

> Indeed, thanks for the link. I have looked deeper into this and made the environment that you have described. The game made has a 1D map.

Nice! This is exactly the type of "simple tests" that you should create to sanity-check new algorithms/implementations :). Good thing it works!

> This is exactly what I am trying to find out! We have talked quite a lot here and I would have been stuck a long time ago without you! Thank you again and could I contact you more privately?

No problem, happy to help :). I am most active on Discord: my tag is "[my-username-in-github]#0001". Feel free to add me there!  

> This is my code for the 1D environment in case anyone ever needs it.

Bit of a nitpick, but I hope you have a personal repository where you store all of this code etc :). It would also help others (and show that you have been productive to future job applications) if you put all of this work into a single, public github repo.
