### ISSUE TITLE
[question] How to add wrapper for enjoy process

### ISSUE THREAD

**Issue by ZY-KK** [DLR-RM/rl-baselines3-zoo#134]
Hi,
As the title said, I would like to test my trained model, but my environment has observation wrapper when training, could you please tell me when I use enjoy.py to test my model, should I add wrapper parameters? if I should, how to add?
Thank you so much!

**Comment by araffin** [comment]
If you use the zoo and specify it during training, it will be automatically used at test time.
If you need to modify it between train and test, you can edit the saved config file in the log folder.
