### ISSUE TITLE
[question] Why the training process did not stop after reach to the timesteps I set

### ISSUE THREAD

**Issue by ZY-KK** [DLR-RM/rl-baselines3-zoo#136]
I set the SAC algorithm, the timesteps I set is 30000, and buffer size is 15000. After reach 30000 timesteps, the process still run and could you please tell me why? Thank you!

**Comment by araffin** [comment]
>fter reach 30000 timesteps, the process still run and could you please tell me why? Thank you!

What do you mean? And what command did you use?

**Comment by ZY-KK** [comment]
I just run train.py, all the parameters are set before

**Comment by Miffyli** [comment]
Please check the [question template](https://github.com/DLR-RM/stable-baselines3/blob/master/.github/ISSUE_TEMPLATE/question.md) fill all the parts and explain expected behaviour but what you get instead.

**Comment by araffin** [comment]
closing as not enough information was provided
