### ISSUE TITLE
[feature request] Hyperparameter optimization improvements

### ISSUE THREAD

**Issue by SammyRamone** [DLR-RM/rl-baselines3-zoo#14]
I played around with the Optuna hyperparameter optimization a bit and some things came to my mind.
I would like to know if you are interested in having anything of this upstream. If so, I would create PRs for it.

### 1. Distributed optimization
Optuna gives the possibility to distribute the study on different machines by using an SQL database ([link](https://optuna.readthedocs.io/en/latest/tutorial/distributed.html)). I tried it out on my fork, and it seemed to work quiet well. This would add another optional parameter for the storage location, but does not require a lot of additional code.

### 2. Optimization direction
Optuna allows to minimize or maximize the return of the objective function. Currently the reward is returned like this:
https://github.com/DLR-RM/rl-baselines3-zoo/blob/29520f89ff4b8d4315cf701e8a04f51389a45576/utils/hyperparams_opt.py#L106
I found it very unintuitive first, that there were negative numbers as results of the trials (as my environment only returns positive rewards). 
I would propose to set the optimization direction to 'maximize' and return the reward as it is. This requires only two lines of code change.

### 3. Save all hyperparameters
Currently only the hyperparameters that are choosen by Optuna are saved to the trial. It can happen that you want to run multiple optimizations with different fixed sets of parameters. In this case you have to keep track of them yourself.
It is possible to add further information to a study (or to a single trial) by using `set_user_attr(key, value)` ([link](https://optuna.readthedocs.io/en/latest/tutorial/attributes.html)).
I think it would be nice to save all fixed hyperparameters, so that it's easier to look up again afterwards. I didn't implement it yet, but I think that it should not require so much code.

By the way, thanks again for stable-baselines, it is really helpful and well documented :)

**Comment by araffin** [comment]
> This would add another optional parameter for the storage location, but does not require a lot of additional code.

This is nice to have but should not be a requirement, in the sense that the previous behavior should still work.

>Optuna allows to minimize or maximize the return of the objective function.
> I found it very unintuitive first, that there were negative numbers as results of the trials (as my environment only returns positive rewards).

I would agree with that one too. This is more "historical" reason. When I started the zoo, Optuna was only made for minimization, hence the trick.


>Save all hyperparameters

sounds also good to me ;) (and #11 is also related to that)

**Comment by SammyRamone** [comment]
> This is nice to have but should not be a requirement, in the sense that the previous behavior should still work.

Yes, of course. It's not a problem, since passing `None` as storage parameter to `create_study` will do the default behavior.
> sounds also good to me ;) (and #11 is also related to that)

Good point, I will save them in the study too.

I will try to do the PRs next week.

**Comment by SammyRamone** [comment]
I had a longer look at 3, but it seems that there is no simple solution for this. There are multiple problems (serializing parameters, adding them to the CSV output file, ...). In the end it would create a lot of code lines and decrease code quality for this very small feature, where I'm not so sure if anybody would actually use this. Therefore I don't think that it makes sense to add this upstream.
