### ISSUE TITLE
load-last-checkpoint does not actually load the last available checkpoint

### ISSUE THREAD

**Issue by SammyRamone** [DLR-RM/rl-baselines3-zoo#141]
**Describe the bug**
When running the enjoy.py script with --load-last-checkpoint it will not load the last available checkpoint but the one which is alphabetically the last one.
The issue arises from following lines 
https://github.com/DLR-RM/rl-baselines3-zoo/blob/96f1a59b407f49a9beccbb1c6948fa502a4717d5/enjoy.py#L101-L104
We take the last entry from `checkpoints` but this is sorted alphabetically, that means the list is ordered like this when we do a checkpoint each 100000 steps:
```
[
"rl_model_10000000_steps.zip",
"rl_model_1000000_steps.zip",
"rl_model_100000_steps.zip",
"rl_model_10100000_steps.zip",
...
"rl_model_9900000_steps.zip"
]
```

Additionally the documentation of `glob` says that the sorting is depended on the filesystem type (https://docs.python.org/3/library/glob.html). 

This issue can be fixed by resorting this array in natural sort order before running line 104.

**Code example**
1. Run training with creating checkpoint each 1000 steps
2. Stop training after 10000 steps
3. Run enjoy with load-last-checkpoint
4. It will load rl_model_9000.zip

**System Info**
Ubuntu 18.04
Python 3.7
Installed from source

**Comment by araffin** [comment]
Hello,
nice catch, I would appreciate a PR that solves that issue ;)
