### ISSUE TITLE
[question] DQN buffer size lower than learning starts

### ISSUE THREAD

**Issue by nikhilrayaprolu** [DLR-RM/rl-baselines3-zoo#147]
https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/dqn.yml#L7
Here for the hyperparameters of DQN, the buffer size is 1e4 whereas learning_starts has a value of 1e5. Does it make sense to have learning_starts be higher than buffer size?

**Comment by araffin** [comment]
Hello,
not really, you are right, i would appreciate a PR that increases the buffer size to 1e5 (originally 1e4 to avoid any ram issue)

**Comment by nikhilrayaprolu** [comment]
Raised the PR at #148
