### ISSUE TITLE
Callbacks missing in hyperparameter optimization

### ISSUE THREAD

**Issue by SammyRamone** [DLR-RM/rl-baselines3-zoo#149]
**Describe the bug**
When running the hyperparameter optimization, any additional/custom callbacks that are specified in the hyperparameter yaml are not started.
The line which is responsible for this is this:
https://github.com/DLR-RM/rl-baselines3-zoo/blob/2af52e18ff5382029ce8398149cb5d20a68edfe3/utils/exp_manager.py#L627
It only starts the eval_callback and not all specified callbacks, as it is done for a normal training here:
https://github.com/DLR-RM/rl-baselines3-zoo/blob/2af52e18ff5382029ce8398149cb5d20a68edfe3/utils/exp_manager.py#L189-L193

I'm not sure if this is a bug or supposed behavior. At least for my use case, this breaks everything. My callback is used to set the goal velocity of a walking robot. Without it, the velocity will stay the same during optimization, leading to parameters that are not actually working when using different velocities.

**Code example**
Just add a callback in the hyperparmeter yaml with a print and start optimization to see, that it is never executed.

**System Info**
* Ubuntu 18.04
* installed from source
* Python 3.7
* Pytorch 1.5.1

**Comment by araffin** [comment]
Hello,

> When running the hyperparameter optimization, any additional/custom callbacks that are specified in the hyperparameter yaml are not started.

in fact, I never add the issue of needing a callback for training, but it seems reasonable to allow the user to pass additional ones ;)

>At least for my use case, this breaks everything. My callback is used to set the goal velocity of a walking robot. Without it, the velocity will stay the same during optimization, leading to parameters that are not actually working when using different velocities.

are you changing the velocity depending on the performance?

**Comment by SammyRamone** [comment]
> in fact, I never add the issue of needing a callback for training, but it seems reasonable to allow the user to pass additional ones ;)

I just don't see any reason why they should not be started during hyperparameter optimization if they are started during training. Furthermore, it is hard to realize that this is the case if the env works without the callback and only results in different rewards.
I think it is quiet common (at least in the direction of DRL for robot motions) to change certain parameters over time (e.g. target speed for walking) to have some kind of curriculum learning. This can be done very well using a callback. So I would be in favor to include the callbacks, or at least print a warning if some are specified.
Either way, I can provide a PR if you want to, it's just a few lines of code to change.

> are you changing the velocity depending on the performance?

No, I was just simply increasing the area from which the command walk velocity was sampled from based on the steps that have passed. In the end, I found out that it was not necessary to this in my case after all :man_shrugging:

**Comment by araffin** [comment]
>  Either way, I can provide a PR if you want to, it's just a few lines of code to change.

Please do =)

> from which the command walk velocity was sampled from based on the steps that have passed

did you need access to the RL model for that? otherwise a gym wrapper should do the work.

**Comment by SammyRamone** [comment]
> > Either way, I can provide a PR if you want to, it's just a few lines of code to change.
> 
> Please do =)

Which solution do you want? Printing a warning message or that the callbacks are just used like in normal training?

> > from which the command walk velocity was sampled from based on the steps that have passed
> 
> did you need access to the RL model for that? otherwise a gym wrapper should do the work.

True, I could have done it with a gym wrapper in this case

**Comment by araffin** [comment]
>callbacks are just used like in normal training?

keeping the same behavior would make more sense, no?

**Comment by SammyRamone** [comment]
> > callbacks are just used like in normal training?
> 
> keeping the same behavior would make more sense, no?

yes I would think so, too

I opened a PR https://github.com/DLR-RM/rl-baselines3-zoo/pull/157
Sorry for taking so long, I*m quiet busy currently

**Comment by araffin** [comment]
>  Sorry for taking so long, I*m quiet busy currently

no worry, everyone is busy ;) Thanks for the PR =)
