### ISSUE TITLE
[Bug?] Trials keep running after passed --n-trials value

### ISSUE THREAD

**Issue by jkterry1** [DLR-RM/rl-baselines3-zoo#153]
When I run start a bunch of processes on a cluster that's each running it's own independent hyperparameter optimizations, e.g. 

`CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=1 nohup python3 train.py --algo ppo --env LunarLanderContinuous-v2 -n 2000000 -optimize --n-trials 150 --sampler tpe --pruner median --study-name $1 --storage mysql://root:dummy@[]/$1 &> ./optimize_logs/optimize_0.out &`

Each process will keep running even after 150 total samples have been evaluated. This certainly does not feel like intended behavior, though perhaps I'm missing something.

**Comment by araffin** [comment]
>Each process will keep running even after 150 total samples have been evaluated. This certainly does not feel like intended behavior, though perhaps I'm missing something.

Do it hangs or continue to evaluate new trials?

that may be because of the plots at the very end (after the study is saved), does it do the same when passing `--no-optim-plots` ?
and do it happens also with smaller number of trials?

**Comment by jkterry1** [comment]
It explicitly continues to evaluate new trials (e.g. up to >200 with 150 listed and 16 jobs). I haven't tried it with less than 100 because that wouldn't be useful for any of my work.

**Comment by araffin** [comment]
Hello,
I've been able to reproduce the behavior, but I'm not sure if it is a bug.
with (I made an example that runs in only few minutes), lauching two processes with:
```
python train.py --algo ppo --env LunarLanderContinuous-v2 -n 1000 -optimize --n-trials 15 --n-evaluations 4 --study-name issue-153 --storage sqlite:///logs/test.db
```

What is happening is simply that every processes will do `n-trials`, so with two processes and `n_trials=15`, it does 30 trials (15 per process).
Maybe more a documentation issue?

**Comment by jkterry1** [comment]
I think you could fix the documentation and call this "fixed", but I don't think that this is the intuitive/reasonable/expected behavior here. It's at least my opinion that the functionality we want should be to apply the limit across multiple processes somehow, like I expected would happen.

**Comment by araffin** [comment]
another note: it seems that this issue come from Optuna, not really the zoo.

**Comment by jkterry1** [comment]
Is the move here to file upstream...?

**Comment by jkterry1** [comment]
I guess filing upstream and changing the docs until if/when optuna sorts it out makes the most sense?

**Comment by araffin** [comment]
> I guess filing upstream and changing the docs until if/when optuna sorts it out makes the most sense?

yes =)

**Comment by jkterry1** [comment]
Per upstream discussion I'll do a PR clarifying this
