### ISSUE TITLE
[Question] Supporting RL libraries other than SB3?

### ISSUE THREAD

**Issue by jkterry1** [DLR-RM/rl-baselines3-zoo#159]
Before I switched to using this repo for hyperparameter tuning I spent ~6 months off and on trying to get my own system working, and between that and discussions with others have become increasingly convinced that DIY RL hyperparameter tuning code is an absolutely cursed idea. As I'm sure you've noticed, I use this code base a tremendous amount for my research. However, I also need to use learning methods in other libraries that involve things that SB3 will never realistically support, e.g. neural fictitious self play based on a fork of the autonomous learning library or CQL (which there is a legitimate production grade implementation of in Tianshou). Accordingly, I have a few questions:

- Do you want to extend rl baselines zoo in a way to more generally include other RL libraries (just for tuning, I don't care about pretrained policies)? E.g. rl baselines3 could have some sort of general API for RL libraries with wrappers for each.
- If I were to fork RL baselines and add support for a different learning library, do you have thoughts on how I could do this?

**Comment by araffin** [comment]
Hello,

>Do you want to extend rl baselines zoo in a way to more generally include other RL libraries (just for tuning, I don't care about pretrained policies)? E.g. rl baselines3 could have some sort of general API for RL libraries with wrappers for each.

I would favor a fork as I'm afraid this would complexify the internals (the same way it was when Keras was supporting both Theano and Tensorflow) and as I cannot maintain the code for any library (one is already quite some work).

For custom algorithms/library, I recommend adapting https://github.com/araffin/rl-handson-rlvs21/blob/main/optuna/sb3_simple.py, this is a simplified version of what is in the zoo that I created for Optuna examples (https://github.com/optuna/optuna-examples)

My student did that for CQL with the library https://github.com/takuseno/d3rlpy for an internal project.

> If I were to fork RL baselines and add support for a different learning library, do you have thoughts on how I could do this?

What do you mean exactly? What should be changed?

**Comment by jkterry1** [comment]
Hey thanks a ton for the dummy script. I'm probably going to use that to work with two other RL library authors to working hyperparameter optimization code there
