### ISSUE TITLE
[Documentation Question] When is a run determined to be crashed for the purpose of future hyperparameter searches?

### ISSUE THREAD

**Issue by jkterry1** [DLR-RM/rl-baselines3-zoo#160]
Right now running 16 optimization runs for on GCP. For whatever reason they've seized for 2 days and I have to reboot the systems. Will these searched hyperparameters count as a run that crashed due to instability (with None return), and in general what precisely will result in that state? I've been looking to figure this out and can't, and independent of me it seems like this is something important to document.

**Comment by araffin** [comment]
> Will these searched hyperparameters count as a run that crashed due to instability (with None return),

I'm not sure. You can check with optuna dashboard but they will still count as "running" if I recall.

>and in general what precisely will result in that state? 

It's hard to tell without much information to reproduce the issue.

**Comment by jkterry1** [comment]
This was explained well in the upstream issue

**Comment by jkterry1** [comment]
Hey thanks a ton for the dummy script. I'm probably going to use that to work with two other RL library authors to working hyperparameter optimization code there
