### ISSUE TITLE
Bug in make type script?

### ISSUE THREAD

**Issue by jkterry1** [DLR-RM/rl-baselines3-zoo#161]
Running the make type script (for PR #140) results in an error I am not able to decipher that does not seem likely to be my fault:

```
justinterry@preacherMan2 rl-baselines3-zoo % make type                                                                                                                                                     
pytype -j auto *.py tests/ scripts/ utils/
Computing dependencies
Analyzing 22 sources with 0 local dependencies
ninja: Entering directory `.pytype'
ninja: error: build.ninja:13: multiple rules generate /Users/justinterry/Documents/master [-w dupbuild=err]

Leaving directory '.pytype'
make: *** [type] Error 1
```

**Comment by araffin** [comment]
Hello,
Have you tried running it using the docker image?

I couldn't reproduce the error locally (and the github action seems to work too).

Could you provide your config?

My config:
Ubuntu 20.04.3 LTS
Python 3.7.9
pytype==2021.8.24

**Comment by jkterry1** [comment]
I'm using macOS 11.15, Python 3.9.5 and pytype 2021.8.24. I haven't tried running it via docker but I can if necessary.
