### ISSUE TITLE
AssertionError: The rl-trained-agents\ppo folder was not found

### ISSUE THREAD

**Issue by learningxiaobai** [DLR-RM/rl-baselines3-zoo#164]
hello，when i ran the enjoy.py, i met these errors:
Traceback (most recent call last):
  File "C:/实验/rl-baselines3-zoo-master/enjoy.py", line 248, in <module>
    main()
  File "C:/实验/rl-baselines3-zoo-master/enjoy.py", line 83, in main
    assert os.path.isdir(log_path), f"The {log_path} folder was not found"
AssertionError: The rl-trained-agents\ppo folder was not found
 python version:3.7,windows
thanks a lot

**Comment by qgallouedec** [comment]
Have you read the dedicated part of the `README.md`?
https://github.com/DLR-RM/rl-baselines3-zoo#enjoy-a-trained-agent

You may have forgot the clone recursively :

```bash
git clone --recursive https://github.com/DLR-RM/rl-baselines3-zoo
```

**Comment by learningxiaobai** [comment]
> Have you read the dedicated part of the `README.md`?
> https://github.com/DLR-RM/rl-baselines3-zoo#enjoy-a-trained-agent
> 
> You may have forgot the clone recursively :
> 
> ```shell
> git clone --recursive https://github.com/DLR-RM/rl-baselines3-zoo
> ```

thanks a lot, i got it
