### ISSUE TITLE
No presentation window

### ISSUE THREAD

**Issue by learningxiaobai** [DLR-RM/rl-baselines3-zoo#167]
hello，
1.when i run：python enjoy.py --algo tqc --env PandaPush-v1--folder rl-trained-agents/ -n 5000
i can't see the presentation window，just data like this：
Episode Reward: -8.00
Episode Length 50
Episode Reward: -7.00
Episode Length 50
Episode Reward: -4.00
Episode Length 50
Episode Reward: -7.00
Episode Length 50
Episode Reward: -7.00
Episode Length 50
Episode Reward: -8.00
Episode Length 50
Episode Reward: -6.00
Episode Length 50
Episode Reward: -7.00
Episode Length 50
Episode Reward: -5.00
Episode Length 50
Episode Reward: -10.00
Episode Length 50
Episode Reward: -5.00
Episode Length 50
Episode Reward: -5.00
Episode Length 50
Episode Reward: -6.00
Episode Length 50
Episode Reward: -7.00
Episode Length 50
Episode Reward: -3.00
do you know why？
2.could you please give me a example running code according to this instruction：
To visualize the result, you can pass --env-kwargs render:True to the enjoy script

**Comment by qgallouedec** [comment]
Hi,

```bash
python enjoy.py --algo tqc --env PandaPush-v1--folder rl-trained-agents/ -n 5000 --env-kwargs render:True
```

**Comment by learningxiaobai** [comment]
> Hi,
> 
> ```shell
> python enjoy.py --algo tqc --env PandaPush-v1--folder rl-trained-agents/ -n 5000 --env-kwargs render:True
> ```

thank you ，i have another question：is that：when i run python scripts/plot_train.py -a tqc -e Panda -y success -f rl-trained-agents/ -w 500 -x steps：
i got nothing：
No data available for rl-trained-agents/tqc\PandaPickAndPlace-v1_1
No data available for rl-trained-agents/tqc\PandaPush-v1_1
No data available for rl-trained-agents/tqc\PandaReach-v1_1
No data available for rl-trained-agents/tqc\PandaSlide-v1_2
No data available for rl-trained-agents/tqc\PandaStack-v1_1
No handles with labels found to put in legend.
do you know why？thanks

**Comment by araffin** [comment]
>  do you know why？thanks

yes, because this line of code was added only after training the agents...

https://github.com/DLR-RM/rl-baselines3-zoo/pull/130/commits/ff58f6698e7c402141393b3837787e0668cdfbfa
