### ISSUE TITLE
Hyperparameter Tuning for Custom Environment.

### ISSUE THREAD

**Issue by JingZhang918** [DLR-RM/rl-baselines3-zoo#168]
I built an environment called StockTradingEnv. I train the model using
```
env_train = DummyVecEnv([lambda: StockTradingEnv(training_data)])
env_test = DummyVecEnv([lambda: StockTradingEnv(test_data)])

model = PPO('MlpPolicy', env, n_epochs=20, gamma= 1, clip_range=0.1, learning_rate=1e-4, seed=0)
model.learn(total_timesteps=1e5)
```
I want to do a grid search. Is there any way that I can achieve this easily?

**Comment by araffin** [comment]
> I want to do a grid search. Is there any way that I can achieve this easily?

Please read the README... and grid search is not recommended at all https://www.jmlr.org/papers/volume13/bergstra12a/bergstra12a.pdf

**Comment by JingZhang918** [comment]
> Please read the README... and grid search is not recommended at all https://www.jmlr.org/papers/volume13/bergstra12a/bergstra12a.pdf

Then how to optimize parameters using zoo?
