### ISSUE TITLE
Saving and loading hyper parameter optimization 

### ISSUE THREAD

**Issue by bebeleme** [DLR-RM/rl-baselines3-zoo#192]
Hi, hyper parameter optimization  takes a lot of time on my system, if i want 1000 trials, is there a way to interrupt optimization (ctrl+c) e.g at trial 300, save it's current state, then load it from saved file and continue from there?

**Comment by qgallouedec** [comment]
I pretty sure you can do it by passing `storage` and `study_name` arg, it would work:

```bash
python train.py --algo <ALGO> --env <ENV> --storage <DATABASE FILE> --study-name <STUDY NAME>
```

For example:

```bash
python train.py --env MountainCarContinuous-v0 --algo ddpg --optimize --study-name "my_study_name" --storage sqlite:///my_database.db
```

This will save all the trials in the database. So you can stop the optimization process at any time and resume it from where it was stopped.

**Comment by qgallouedec** [comment]
(To resume optimization, just re-run the command)

**Comment by bebeleme** [comment]
Ok, that will be perfect for my needs. Thank you for your quick response.
