### ISSUE TITLE
Hyperparameter optimization of activation function

### ISSUE THREAD

**Issue by SammyRamone** [DLR-RM/rl-baselines3-zoo#2]
**Describe the bug**
When using hyperparameter optimization with PPO (but should be the same with other algorithms) Optuna throws following warning:
`optuna/distributions.py:331: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains <class 'torch.nn.modules.activation.Tanh'> which is of type type.`
From Optuna documentation (https://readthedocs.org/projects/optuna/downloads/pdf/latest/):

> Not all types are guaranteed to be compatible with all storages.  It is recommended to restrict the types of the choices to None,bool,int,float and str

**Code example**
The bug can be reproduced by running train.py with optimization activated.
The problem comes from this line:
https://github.com/DLR-RM/rl-baselines3-zoo/blob/221650104d9235f1a7c8941895ba659ecfd4f648/utils/hyperparams_opt.py#L160

I would propose to fix it similar to how the network structure is handled. First using just strings and then using the corresponding class afterwards
https://github.com/DLR-RM/rl-baselines3-zoo/blob/221650104d9235f1a7c8941895ba659ecfd4f648/utils/hyperparams_opt.py#L154
https://github.com/DLR-RM/rl-baselines3-zoo/blob/221650104d9235f1a7c8941895ba659ecfd4f648/utils/hyperparams_opt.py#L169-L172

**System Info**
Python 3.7
Optuna installed via pip on version 1.4.0

**Comment by araffin** [comment]
Hello,

Thanks for reporting the issue, but as mentioned by the message, it is only a warning.
We are not using "persistent storage" for now, so it's not really an issue.

>I would propose to fix it similar to how the network structure is handled. First using just strings and then using the corresponding class afterwards

Please go ahead ;) Don't forget to read the SB3 contributing guide ;)

**Comment by SammyRamone** [comment]
Yes, it's only a warning. Still it's easy to get rid of and other new users are less confused :)
