### ISSUE TITLE
[question] Checkpoints not saved?

### ISSUE THREAD

**Issue by stobias123** [DLR-RM/rl-baselines3-zoo#215]
Running with `--save-freq 2500` - and I can't seem to find checkpoints anywhere.. Where should I expect to find my models?

**Code example**
```shell
#!/bin/bash
mkdir -p /data
python train.py --algo ppo --env Robocode-v2 \
                           --gym-packages gym_robocode \
                           --tensorboard-log /data/stable-baselines/  \
                           --save-freq 2500 \
                           -f /data/logs \
                           --optimization-log-path /data/opt_logs\
```

**Comment by stobias123** [comment]
Everything is in the `logs` directory. I read through the [colab](https://colab.research.google.com/github/Stable-Baselines-Team/rl-colab-notebooks/blob/sb3/rl-baselines-zoo.ipynb#scrollTo=-fHBq73665yD) notebook and things made more sense.

**Comment by bdytx5** [comment]
Where at in logs? Cant seem to find it

**Comment by bdytx5** [comment]
Where at in logs? Cant seem to find it
