### ISSUE TITLE
Add a callback to log raw stats

### ISSUE THREAD

**Issue by vwxyzjn** [DLR-RM/rl-baselines3-zoo#217]
**Describe**

SB3 only logs the mean episodic return (i.e., `rollout/ep_rew_mean`), which is good enough in most cases. However, sometimes we may want the raw episodic return that is unaveraged. In my case, I was trying to compare my raw episodic return with `rollout/ep_rew_mean`, and it would look like something below, where SB3's orange curve would be much smoother because of the average operation.

![image](https://user-images.githubusercontent.com/5555347/157102849-be47d08b-bb67-45a1-a2ec-1d05bdd16822.png)

Maybe it's worth also logging the raw stats, or at least give an option to.

#216 tracks the progress.

**Comment by araffin** [comment]
closed in #216
