### ISSUE TITLE
stable-baselines[extra] requirement breaks Windows support

### ISSUE THREAD

**Issue by vadim0x60** [DLR-RM/rl-baselines3-zoo#232]
If you run `pip install -r requirements.txt` on Windows, the installation will fail while installing stable-baselines[extra]. The `extra` option is applied recursively, leading to a very deep dependency tree, including packages that don't support Windows. Removing the `extra` should fix this.

**Comment by araffin** [comment]
> including packages that don't support Windows. 

which packages are not supported by windows?

**Comment by araffin** [comment]
Could you submit a PR that adds a note for installation for windows users (I think you can get pybullet with conda forge)

**Comment by vadim0x60** [comment]
The culprit that broke it for me is `pandas > hypothesis > attrs > pytest > pluggy > importlib-metadata > zipp > sphinx > sphinxcontrib-applehelp > mypy > psutil > mock > twine > readme-renderer > bleach > tinycss2 > sphinx-rtd-theme > sphinxcontrib-httpdomain > Sphinx > sphinxcontrib-htmlhelp > html5lib > genshi > setuptools > jaraco.packaging > rst.linker > pytest-checkdocs > pytest-cov > pytest-xdist > execnet > pre-commit > virtualenv > filelock > sphinx-autodoc-typehints > nptyping > black > platformdirs > pytest-mock > tox > towncrier > incremental > twisted > Automat > Twisted > twistedchecker > pylint > isort > requirementslib > vistir > pytype`

I will check that everything installs on Window if I remove `extra` and submit a PR

**Comment by araffin** [comment]
> I will check that everything installs on Window if I remove extra and submit a PR

you probably to remove more. I managed to work with SB3 on windows, but that was on that branch: https://github.com/DLR-RM/rl-baselines3-zoo/blob/misc/veridream/requirements.txt

**Comment by vadim0x60** [comment]
I just checked, the only package that doesn't support Windows is `pytype`. It occures in the depths of the `pandas` dependency tree, as I mentioned above, and it is also a direct dependency of `stable-baselines3[test]`. If you replace `stable-baselines3[extra,test,docs]` with `stable-baselines3[docs]` it installs fine.

**Comment by vadim0x60** [comment]
But the question is how important are those options? I presume `tests` aren't important for the end user (I can be wrong, of course), but If some of the functionality stops working because I removed `extras`, we should document what exactly doesn't work on Windows. If it isn't important, then it's better to just remove it from `requirements.txt` regardless of the platform.

**Comment by araffin** [comment]
> But the question is: how important are those options? I presume tests aren't important for the end user (I can be wrong, of course), 

The only requirement is `stable-baselines3`, the rest is for atari-games, visualization (extra) and development (tests, docs).
To use the RL Zoo, you only need `stable-baselines3` but you won't have access to all envs.

**Comment by araffin** [comment]
should be fixed with the rl zoo released as a package (for minimal support, you don't need `requirements.txt`, `pip install rl_zoo3` or `pip install -e .` from source)
