### ISSUE TITLE
[question] Why not use `NopPruner` when pruner is set to `"none"`

### ISSUE THREAD

**Issue by qgallouedec** [DLR-RM/rl-baselines3-zoo#233]
When you run the optimization with **no pruner**, the code uses a median pruner initialized so that it cannot prune :

https://github.com/DLR-RM/rl-baselines3-zoo/blob/73f0d6ab144403541014217910adcd1423b53f28/utils/exp_manager.py#L622

 Is there any reason not to use `NopPruner` instead?

**Comment by araffin** [comment]
Hello,

> Is there any reason not to use NopPruner instead?

Good point, I think it didn't exist when I initially wrote the code, but would definitely appreciate a PR ;)
