### ISSUE TITLE
No data available for logs/ppo\RobotReach-v1_1 No handles with labels found to put in legend.

### ISSUE THREAD

**Issue by learningxiaobai** [DLR-RM/rl-baselines3-zoo#247]
Hello, I have trained  my RobotReach using PPO, and the success rate is 1,it is saved in logs, but when I run
`python scripts/plot_train.py -a ppo -e RobotReach -y success -f logs/` ,i got no thing but:
No data available for logs/ppo\RobotReach-v1_1 No handles with labels found to put in legend.
What's wrong? thanks.

**Comment by learningxiaobai** [comment]
I can get the reward curve, but I can't get the success rate curve,why?thanks.

**Comment by araffin** [comment]
Hello,
you actually need to activate success rate logging here: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/utils/exp_manager.py#L528

Anyway, I would recommend you to use the eval callback for a better estimate of the true performance.

**Comment by araffin** [comment]
> Hello， how can I activate the success rate？
>  i just put success rate in monitor_kwargs ={ }，such as monitor_kwargs = {"success rate"}；


if you read the API documentation (https://stable-baselines3.readthedocs.io/en/master/common/monitor.htmlà, yes, you need to pass `monitor_kwargs = ("success_rate",)`.

>  btw, can you give me more detailed information about the eval callback?

This is the `eval-freq` parameter in the zoo. You can read about it in our doc.

And if you read the code (don't be afraid of that ;)), it will automatically log the success rate if available: https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/callbacks.py#L369

**Comment by learningxiaobai** [comment]
> > Hello， how can I activate the success rate？
> > i just put success rate in monitor_kwargs ={ }，such as monitor_kwargs = {"success rate"}；
> 
> if you read the API documentation ([https://stable-baselines3.readthedocs.io/en/master/common/monitor.htmlà](https://stable-baselines3.readthedocs.io/en/master/common/monitor.html%C3%A0), yes, you need to pass `monitor_kwargs = ("success_rate",)`.
> 
> > btw, can you give me more detailed information about the eval callback?
> 
> This is the `eval-freq` parameter in the zoo. You can read about it in our doc.
> 
> And if you read the code (don't be afraid of that ;)), it will automatically log the success rate if available: https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/callbacks.py#L369

**Comment by learningxiaobai** [comment]
> > Hello， how can I activate the success rate？
> > i just put success rate in monitor_kwargs ={ }，such as monitor_kwargs = {"success rate"}；
> 
> if you read the API documentation ([https://stable-baselines3.readthedocs.io/en/master/common/monitor.htmlà](https://stable-baselines3.readthedocs.io/en/master/common/monitor.html%C3%A0), yes, you need to pass `monitor_kwargs = ("success_rate",)`.
> when I set `monitor_kwargs = ("success_rate",)，i met error when training：
File "C:\ProgramData\Anaconda3\envs\robot_gym\lib\site-packages\stable_baselines3\common\env_util.py", line 92, in _init
    env = Monitor(env, filename=monitor_path, **monitor_kwargs)
TypeError: type object argument after ** must be a mapping, not set
what's the problem?

**Comment by qgallouedec** [comment]
Try with 

```python
monitor_kwargs = dict(info_keywords=("success_rate",))
```

**Comment by araffin** [comment]
>  KeyError: 'success_rate'

so, the correct one is:

```python
monitor_kwargs = dict(info_keywords=("is_success",))
```

This is the key that your environment must set in the info dict.

Thanks @qgallouedec , my example was wrong, but the code linked was right ;)
