### ISSUE TITLE
How can i train with Her?

### ISSUE THREAD

**Issue by learningxiaobai** [DLR-RM/rl-baselines3-zoo#251]
Hello,when I python train.py --algo her --env PandaStack-v1 --tensorboard-log /tmp/stable-baselines/
 I found that:
train.py: error: argument --algo: invalid choice: 'her' (choose from 'a2c', 'ddpg', 'dqn', 'ppo', 'sac', 'td3', 'qrdqn', 'tqc')
Does this mean that I can't train with her? What's wrong? Thanks.

**Comment by learningxiaobai** [comment]
I know that Her is Reply buffer, so I have defined 
replay_buffer_class: HerReplayBuffer in tqc, but when I trained with tqc, the logs are in the /logs/tqc, not in the /logs/tqc.
what's wrong?

**Comment by qgallouedec** [comment]
>  the logs are in the /logs/tqc, not in the /logs/tqc. This means that her Reply buffer didn't use

Can you clarify this?

**Comment by learningxiaobai** [comment]
> > the logs are in the /logs/tqc, not in the /logs/tqc. This means that her Reply buffer didn't use
> 
> Can you clarify this?
I mean that I can't find the log file for Her training， How can I train by her？

**Comment by qgallouedec** [comment]
I can see that you want to train with PandaStack. Default hyperparameters with this env includes HER replay buffer.

See

https://github.com/DLR-RM/rl-baselines3-zoo/blob/3c1ba9596bb4cce2a64ccc70a02073ba2853b6ff/hyperparams/tqc.yml#L195 

and 

https://github.com/DLR-RM/rl-baselines3-zoo/blob/3c1ba9596bb4cce2a64ccc70a02073ba2853b6ff/hyperparams/tqc.yml#L240

So you only need to run

```
python train.py --algo tqc --env PandaStack-v1
```

> **Note**
> Don't expect the training to converge with the default hyperpameters. It seems that the task is too complex for the implemented algorithms.

**Comment by learningxiaobai** [comment]
Thanks a lot， I have trained the  --algo tqc --env PandaStack-v1 many times but failed.
 Do you have any suggestions for -algo tqc --env PandaStack-v1?

**Comment by qgallouedec** [comment]
> Thanks a lot， I have trained the --algo tqc --env PandaStack-v1 many times but failed.

What do you mean by "failed"? Is an exception raised or do you just see that the success rate is not increasing?

**Comment by learningxiaobai** [comment]
> > Thanks a lot， I have trained the --algo tqc --env PandaStack-v1 many times but failed.
> 
> What do you mean by "failed"? Is an exception raised or do you just see that the success rate is not increasing?
the success rate is not increasing,always zero

**Comment by qgallouedec** [comment]
Okay, so the issue you raised is solved, you can close it.

Making the staking task converge is difficult because it is a task that requires a high level of prior exploration due to the sparsity of the reward function. You won't be able to make the agent learn it with the algorithms currently implemented in SB3. I advise you to look at algorithms designed for hard exploration problems which are based on intrinsic motivation for example:

https://arxiv.org/pdf/1705.05363.pdf

**Comment by learningxiaobai** [comment]
> Okay, so the issue you raised is solved, you can close it.
> 
> Making the staking task converge is difficult because it is a task that requires a high level of prior exploration due to the sparsity of the reward function. You won't be able to make the agent learn it with the algorithms currently implemented in SB3. I advise you to look at algorithms designed for hard exploration problems which are based on intrinsic motivation for example:
> 
> https://arxiv.org/pdf/1705.05363.pdf

Thanks
