### ISSUE TITLE
Commit message of utils.push_to_hub is always "Initial commit"

### ISSUE THREAD

**Issue by ernestum** [DLR-RM/rl-baselines3-zoo#253]
**Describe the bug**
The commit message of the hugginface upload is always "Initial commit" even when an upload is run multiple times. This can be confusing when looking at the commit history of the HF repo.

**Code example**
Run this command twice and then look at the resulting HF repo:
```
python -m utils.push_to_hub --algo ppo --env <some_env> -orga <some_orga>
```

**Comment by araffin** [comment]
good point adding a `-m` argument should solve this issue.
