### ISSUE TITLE
[Question] Difference between environment with wrapper or none

### ISSUE THREAD

**Issue by ameliacode** [DLR-RM/rl-baselines3-zoo#265]
Hi I am playing around with hopper bullet gym right now.

I just happened to know this that without wrapper like make vec env,  hopper seems to hopping around in the origin.
However, when I wrap the environment, hopper seems to work pretty well.

I kinda don't understand between these two. :(
Is there any way to train this environment without vectorized environment wrapper?

**Comment by qgallouedec** [comment]
Even if you don't wrap the environment in a VecEnv yourself, SB3 does it for you:

https://github.com/DLR-RM/stable-baselines3/blob/d68f0a2411766beb6da58ee0e989d1a6a72869bc/stable_baselines3/common/base_class.py#L163

So I'm not sure I understand your problem.

**Comment by qgallouedec** [comment]
Next time, please make sure to fill the issue template, especially the _minimal example to reproduce the bug_.
