### ISSUE TITLE
[Question] Registering Custom Env

### ISSUE THREAD

**Issue by Vincentlim7** [DLR-RM/rl-baselines3-zoo#272]
Hi,

I'm trying to use rl-baselines3-zoo to train an agent in one of my custom environment, but I'm having trouble registering my env.

The readme says :

1. edit utils/import_envs.py and register your environment here
2. add a section for it in the hyperparameters file (hyperparams/algo.yml)

So in the same directory as `import_envs.py`, I have created a directory `src` in which I have put my codes and an `Environment.py` file.

In the `import_envs.py` file, I have imported my file :
```
try:
    import src.Environment  # pytype: disable=import-error
except ImportError:
    custom_Env = None
```
And I tried to register my env with :
```
register(
    id="CustomEnv-v1",
    entry_point="src.Environment",
)
```
But I have an error as **entry_point** must be a string containing **:** like **"gym.envs.classic_control:CartPoleEnv"** as it is splitted using **":"**.

I have tried using the **create_no_vel_env()** function like so :
```
register(
    id="CustomEnv-v1"
    entry_point=create_no_vel_env(id),
)
```
But I am having the following error :
```
Traceback (most recent call last):
  File "/home/vlim/Workspace/rl-baselines3-zoo/train.py", line 231, in <module>
    results = exp_manager.setup_experiment()
  File "/home/vlim/Workspace/rl-baselines3-zoo/utils/exp_manager.py", line 175, in setup_experiment
    self.create_callbacks()
  File "/home/vlim/Workspace/rl-baselines3-zoo/utils/exp_manager.py", line 453, in create_callbacks
    self.create_envs(self.n_eval_envs, eval_env=True),
  File "/home/vlim/Workspace/rl-baselines3-zoo/utils/exp_manager.py", line 538, in create_envs
    env = make_vec_env(
  File "/home/vlim/anaconda3/envs/work/lib/python3.10/site-packages/stable_baselines3/common/env_util.py", line 105, in make_vec_env
    return vec_env_cls([make_env(i + start_index) for i in range(n_envs)], **vec_env_kwargs)
  File "/home/vlim/anaconda3/envs/work/lib/python3.10/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 25, in __init__
    self.envs = [fn() for fn in env_fns]
  File "/home/vlim/anaconda3/envs/work/lib/python3.10/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 25, in <listcomp>
    self.envs = [fn() for fn in env_fns]
  File "/home/vlim/anaconda3/envs/work/lib/python3.10/site-packages/stable_baselines3/common/env_util.py", line 80, in _init
    env = gym.make(env_id, **env_kwargs)
  File "/home/vlim/anaconda3/envs/work/lib/python3.10/site-packages/gym/envs/registration.py", line 238, in make
    return registry.make(id, **kwargs)
  File "/home/vlim/anaconda3/envs/work/lib/python3.10/site-packages/gym/envs/registration.py", line 130, in make
    env = spec.make(**kwargs)
  File "/home/vlim/anaconda3/envs/work/lib/python3.10/site-packages/gym/envs/registration.py", line 88, in make
    env = self.entry_point(**_kwargs)
  File "/home/vlim/Workspace/rl-baselines3-zoo/utils/import_envs.py", line 53, in make_env
    env = gym.make(env_id)
  File "/home/vlim/anaconda3/envs/work/lib/python3.10/site-packages/gym/envs/registration.py", line 238, in make
    return registry.make(id, **kwargs)
  File "/home/vlim/anaconda3/envs/work/lib/python3.10/site-packages/gym/envs/registration.py", line 129, in make
    spec = self.spec(path)
  File "/home/vlim/anaconda3/envs/work/lib/python3.10/site-packages/gym/envs/registration.py", line 139, in spec
    if ":" in path:
TypeError: argument of type 'builtin_function_or_method' is not iterable
```

For the `hyperparams/algo.yml` file, I have tried adding :
```
CustomEnv-v1:
  n_timesteps: !!float 1e5
  policy: 'MlpPolicy'
  policy_kwargs: "dict(net_arch=[256, 256])"
```
However, I am not sure if I got this right, are values stated below **CustomEnv-v1**  fixed hyperparameters that won't be optimized ?

**Comment by araffin** [comment]
> So in the same directory as import_envs.py, I have created a directory src in which I have put my codes and an Environment.py file.

You should create a python package, not just put it in a directory (well it is possible but not recommended)

You can take a look at https://github.com/osigaud/my_gym for instance.

> But I have an error as entry_point must be a string containing : like "gym.envs.classic_control:CartPoleEnv" as it is splitted using ":".

if you look at the example, `entry_point="src.Environment",` is not enough, you need to use the `:` to specify the class inside the `Environment.py` file (I would also recommend you to use lowercase only with filenames to avoid confusion).

**Comment by Vincentlim7** [comment]
Sorry for the late reply and thank you for your answer !
I managed to resolve my issue registering my custom env by following your instructions.

For my second questions,  in any `hyperparams/algo.yml` file, what do the values below each environment name like in the following code represent ? Are they fixed hyperparameters that won't be optimized ? 

```
CustomEnv-v1:
  n_timesteps: !!float 1e5
  policy: 'MlpPolicy'
  policy_kwargs: "dict(net_arch=[256, 256])"
```

**Comment by Vincentlim7** [comment]
I closed the issue by mistake, sorry

**Comment by araffin** [comment]
> Are they fixed hyperparameters that won't be optimized ?

are you talking about hyperparameter optimization with Optuna.
The hyperparameters in the file are usually the best setting found so far for the env.
Depending on what you commented out or not, they might be optimized or not, you need to take a look at the hyperparameter sampling in `utils` folder.

**Comment by Vincentlim7** [comment]
Yes, I was talking about optimization with Optuna.
I understand, thank you for your answer !

I have a last question about hyperparameters optimisation with Optuna.
As written in the read.me, I have taken a look at the `utils/hyperparams_opt.py`.

```
def sample_dqn_params(trial: optuna.Trial) -> Dict[str, Any]:
    """
    Sampler for DQN hyperparams.

    :param trial:
    :return:
    """
    gamma = trial.suggest_categorical("gamma", [0.9, 0.95, 0.98, 0.99, 0.995, 0.999, 0.9999])
    learning_rate = trial.suggest_loguniform("learning_rate", 1e-5, 1)
    batch_size = trial.suggest_categorical("batch_size", [16, 32, 64, 100, 128, 256, 512])
    buffer_size = trial.suggest_categorical("buffer_size", [int(1e4), int(5e4), int(1e5), int(1e6)])
...
```
If I understand the code properly, do the arrays for each hyperparameters represent the values that will be tested ?
And the combination of hyperparameters sampled in those arrays that will return the best performance would be those saved in the previous `hyperparams/algo.yml` previously mentioned ?

If I take gamma for instance, in this code, this hyperparameter will be optimized with the values [0.9, 0.95, ..., 0.9999], and values not present in the array like 0.8 won't be tested, is that right ?
And If I know that the best value in my case would be either 0.98, 0.99 or 0.995, can I reduce the array to those values only to shorten the total optimization time ?

**Comment by araffin** [comment]
I would recommend you to take a look at our ICRA tutorial, we had a presentation and notebook about hyperparameter optimization with optuna:
- video: https://www.youtube.com/watch?v=AidFTOdGNFQ&list=PL42jkf1t1F7etDiYXWC5Q77yIuVYhXNoy&index=6
- slides: https://araffin.github.io/slides/icra22-hyperparam-opt/
- website: https://araffin.github.io/tools-for-robotic-rl-icra2022/

> do the arrays for each hyperparameters represent the values that will be tested ?

yes

> would be those saved in the previous hyperparams/algo.yml previously mentioned ?

not automatically yet (see issue https://github.com/DLR-RM/rl-baselines3-zoo/issues/121)


> array like 0.8 won't be tested, is that right ?

yes

>  can I reduce the array to those values only to shorten the total optimization time ?

yes, but you usually don't know that in advance.

**Comment by Vincentlim7** [comment]
Thank you !

**Comment by bertanimre** [comment]
Hello,

I am pretty new to Github. So, I hope I am asking my question in the correct place because it is directly related to the tutorial you mentioned. 

I made minor modifications to "Part III: Automatic Hyperparameter Tuning" to optimize the hyperparameters of my custom environment (for instance, I used my custom environment in the "Config" and "Exercise (10 minutes): Define the objective function" sections instead of "CartPole-v1"). I also used "sample_ppo_params(trial: optuna.Trial) -> Dict[str, Any]" from 
rl-baselines3-zoo for my comprehensive parameters.

I think it is an easy and straightforward way to optimize hyperparameters of custom environments (thank you for the tutorial again). 

But I have a problem. As you mentioned "#Sometimes, random hyperparams can generate NaN" under the "Exercise (10 minutes): Define the objective function" section, I got NaN values. Do you have any suggestions for this problem?

Note 1: It might be an Optuna issue but I couldn't find anything useful on its GitHub page.
Note 2: My practical (probably silly) solution is raising optuna.exceptions.TrialPruned() instead of returning float("nan"). I attached a picture of this note.

Thanks in advance.

Best regards,
Bertan
![Solution](https://user-images.githubusercontent.com/51299715/190685271-5e903698-2ae8-4ba5-8b48-6b952d0fb411.PNG)

**Comment by araffin** [comment]
> But I have a problem. As you mentioned "#Sometimes, random hyperparams can generate NaN" under the "Exercise (10 minutes): Define the objective function" section, I got NaN values. Do you have any suggestions for this problem?

See https://github.com/DLR-RM/rl-baselines3-zoo/issues/156#issuecomment-910097343
we catch the error and treat the trial as "pruned".

**Comment by bertanimre** [comment]
Sorry for missing this issue and thank you for your quick response @araffin.
It is what I was exactly looking for!

Best regards,
Bertan

**Comment by bdytx5** [comment]
Full example (ddd_envs is a directory added in rl_zoo3 directory) 

try:
    import sys
    sys.path.append("/home/brett/Desktop/rlzoo/rl-baselines3-zoo/rl_zoo3")
    from ddd_envs.fb_env import FBEnv  # pytype: disable=import-error
    register(
    # unique identifier for the env `name-version`
    id="ddd_fb-v1",
    # path to the class for creating the env
    # Note: entry_point also accept a class as input (and not only a string)
    entry_point=FBEnv,
    # Max number of steps per episode, using a `TimeLimitWrapper`
    max_episode_steps=500,
    )

except Exception as e:
    print("failed to import dddfb env")
    print(str(e))
    FBEnv = None

**Comment by qgallouedec** [comment]
Which versions of gym/gymnasium/sb3 are you using?

**Comment by qgallouedec** [comment]
I'm pretty sure you use gymnasium<0.28. Make sure to upgrade to gymnasium=0.28.1.

**Comment by Melanol** [comment]
> I'm pretty sure you use gymnasium<0.28. Make sure to upgrade to gymnasium=0.28.1.

Yes, It downgraded because the tutorial wanted 0.26.0:
```python
from setuptools import setup

setup(
    name="gym_examples",
    version="0.0.1",
    install_requires=["gymnasium==0.26.0", "pygame==2.1.0"],
)
```
Fixed.
