### ISSUE TITLE
VecNormalize: training should be set to False for eval environments (?)

### ISSUE THREAD

**Issue by pchalasani** [DLR-RM/rl-baselines3-zoo#275]
**Describe the bug**
I don't know if this was intentional, but I do not expect normalization stats to be updated in an evaluation environment (either in an EvalCallback or in a post-train evaluation env). This can be achieved by setting `training = False` as shown below, inside the `_maybe_normalize()` function in `exp_manager.py`. If it was intentional to allow normalization stats to be updated in an eval env, then at least there should be an option to dis-allow it. 

**Code example**
This is not a code to reproduce the bug, but rather a suggestion of what to fix:
At [this line](https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/utils/exp_manager.py#L505) we should have something like this:
```
            if eval_env:
                if len(local_normalize_kwargs) > 0:
                    local_normalize_kwargs["norm_reward"] = False
                    local_normalize_kwargs["training"] = False
                else:
                    local_normalize_kwargs = {"norm_reward": False,
                                              "training": False}
```

**Additional context**
I was migrating my train + eval code to use the `ExperimentManager` and I noticed this while trying to match my results across the migration.

**Comment by araffin** [comment]
Hello,
good point, we would welcome a PR that solves this issue ;)
ps: as we synchronise the stats at every evaluation, this should not change previous results much.

**Comment by araffin** [comment]
when using enjoy, this is already the case: https://github.com/DLR-RM/rl-baselines3-zoo/blob/89d4e0c757f2309d506f32b6bf97eaaddf091209/utils/utils.py#L246

**Comment by pchalasani** [comment]
> when using enjoy, this is already the case:
> 
> https://github.com/DLR-RM/rl-baselines3-zoo/blob/89d4e0c757f2309d506f32b6bf97eaaddf091209/utils/utils.py#L246

Yes `enjoy.py` is fine. With this fix, one can expect to see *exactly identical* results between an evaluation produced by an `EvalCallback` during training and those produced in post-train evaluation (e.g. in `enjoy.py` or similar), assuming evaluation is totally deterministic, and the post-train eval is using the same policy as the one in the eval checkpoint.
