### ISSUE TITLE
Tensorboard is not working properly

### ISSUE THREAD

**Issue by Melanol** [DLR-RM/rl-baselines3-zoo#277]
Tensorboard is not working properly even for provided examples like `python train.py --algo ppo --env CartPole-v1 --tensorboard-log /tmp/stable-baselines/`. It starts normally, and then this happens:

![Screenshot from 2022-08-10 00-59-56](https://user-images.githubusercontent.com/33939307/183750093-73cbe600-4e61-4262-9023-d2b3849a9116.png)

I don't even see tensorboard log files in the folder, only .cvs files, and I don't really know how tensorboard works with these.

**Comment by qgallouedec** [comment]
What makes you say it doesn't work? That the plots are constants?
For CartPole the episode lenght is not intended to change, and PPO reaches the max reward (of 500) before the first evalutation.

**Comment by Melanol** [comment]
@qgallouedec I guess I was looking at different graphs: normally-looking rollout before eval emerged, and then eval:
![Screenshot from 2022-08-10 01-25-10](https://user-images.githubusercontent.com/33939307/183755079-fe17df77-518e-42b3-a139-b3003993f6e9.png).
