### ISSUE TITLE
Enviroment not closed during hyperparameter optimization

### ISSUE THREAD

**Issue by SammyRamone** [DLR-RM/rl-baselines3-zoo#283]
**Describe the bug**
When hyperparameter optimization is used, first the training environments are created to get information about the action space. These environments are not further used but they are not closed. This leads in my custom environment to having zombie processes (which take up memory an create CPU load). My understanding is that a gym environment can expect to have its `.close()` method called to clean up.
Additionally, it seems to be a waste of performance to start `self.n_envs` environments only to get the dimension of the action space. In my case, I need to start an instance of the Webots simulator for each env and I use 8 envs. So this results in a long start time to launch these envs which are just not used afterwards.
This issue is probably only affecting certain custom envs which rely on the `close()` method, but it is also simple to fix.

**Code example**
The relevant code part:
https://github.com/DLR-RM/rl-baselines3-zoo/blob/8e4fa9f563da9db62c9bd18b9bbd5373260f2644/utils/exp_manager.py#L181-L189
I propose to add a `or self.optimize_hyperparameters`in line 181 to only create a single environment and to add a `env.close()` in line 189 before returning `None`

**Comment by araffin** [comment]
Hello,

yes, `close()` is only called after each trial not when retrieving the action space.

> , it seems to be a waste of performance to start self.n_envs environments only to get the dimension of the action space. In

it is... but do you have a better way to retrieve the action space without creating an instance?

>  I propose to add a or self.optimize_hyperparametersin line 181 to only create a single environment and to add a env.close() in line 189 before returning None

sounds good, please go ahead =)

**Comment by SammyRamone** [comment]
> > , it seems to be a waste of performance to start self.n_envs environments only to get the dimension of the action space. In
> 
> it is... but do you have a better way to retrieve the action space without creating an instance?

I don't think there is a way to get completely around it. For example, in my case the action space depends on the env kwargs, therefore it can not be known before creating one. I guess that reducing it to creating a single environment is good enough. It is still not much in comparison to how long hyperparameter optimization takes overall :shrug: 

> > I propose to add a or self.optimize_hyperparametersin line 181 to only create a single environment and to add a env.close() in line 189 before returning None
> 
> sounds good, please go ahead =)

Okay, I will create a PR later today
