### ISSUE TITLE
[Question] Making plots with a custom environment

### ISSUE THREAD

**Issue by silvdureanu** [DLR-RM/rl-baselines3-zoo#288]
I can successfully train my custom environment, but I cannot seem to find a way to link my environment to the provided plotting scripts - I've noticed that the syntax for the environment name is also different in the  plotting examples compared to training. Where do I need to register my environment for this to work?

**Comment by araffin** [comment]
Hello,
could you elaborate on what you are doing exactly? and what have you tried?

**Comment by silvdureanu** [comment]
Hi, sorry for not being clearer - I'm trying to run the plot scripts described in the README (all_plots.py and plot_train.py). I have a custom environment registered as:
```register(
    id='customenv-v0',
    entry_point='customgym.envs:CustomEnv',
)
```

I'm trying to run the scripts after training on the environment with 

`python scripts/plot_train.py -a ppo_lstm -e CustomEnv -y success -f logs/
`
But I only get a blank plot without any datapoints. 

I think this may be related to another issue I've just noticed - Tensorboard is also not showing any data except for what it gets during the periodic evals. It seems that nothing is being written to the logs during training, even if I change the --log-interval argument.

**Comment by araffin** [comment]
> python scripts/all_plots.py -a ppo_lstm -e CustomEnv -f logs/ 

should be -e customenv (should be case sensitive).

> - Tensorboard is also not showing any data except for what it gets during the periodic evals.

But it works with built-en envs, right?

**Comment by silvdureanu** [comment]
Thank you, that was it for the plot scripts, they render correctly now. 



> But it works with built-en envs, right?

Yes, it does. What do I need to add to enable it for the custom environment? I've tried  the VecMonitor wrapper, but it doesn't seem to affect the Tensorboard logs.

**Comment by araffin** [comment]
> What do I need to add to enable it for the custom environment?

Nothing normally, the RL Zoo automatically wrap your env with a monitor wrapper, you can take a look at the logs and check that the log file is created.

Closing as the original question was answered, and the rest seems to be related to custom env, not SB3 / RL Zoo.
