### ISSUE TITLE
Is the feat/pretrain branch going to be merged into master [question]?

### ISSUE THREAD

**Issue by skervim** [DLR-RM/rl-baselines3-zoo#29]
As stated in the issue header, I'm wondering whether the branch containing the `pre-training` logic is going to be merged into `master` eventually or is going to stay like it is only for informational purposes. 
Kind regards,
Skervim

**Comment by araffin** [comment]
Hello,
I was mostly testing it but there is no plan yet to merge it. I'm not completely satisfied by it and would prefer to focus on other things first.

**Comment by skervim** [comment]
Thanks for the quick answer!
