### ISSUE TITLE
[documentation] Fix link to `hyperparams_opt.py`  in README.md

### ISSUE THREAD

**Issue by tobirohrer** [DLR-RM/rl-baselines3-zoo#293]
**Describe the bug**
Link to `hyperparams_opt.py` in README.md does not work. It points to `/utils` folder which does not exist.

**Additional context**
I would create a PR which fixes the link to the file

**Comment by qgallouedec** [comment]
Good catch. We would be glad to receive your PR. We should also look to see if there are any other links that have the same problem.

**Comment by araffin** [comment]
yes, I think we need to update SB3 doc too, related to #292
