### ISSUE TITLE
[Feature request] Parsing train's arguments from a list of strings

### ISSUE THREAD

**Issue by richter43** [DLR-RM/rl-baselines3-zoo#297]
Now that rl-baselines3-zoo is a package and the `train` function can be imported, I'd like to introduce the following feature

### Current workflow
The learning is performed by calling a standalone python process such as:

`python train.py <arguments>`

### Desired workflow

In an interactive programming environment such as jupyter notebooks I'd like it to behave as:

```
from rl_zoo3.train import train

argument_list: List[str] = [...]

train(argument_list)
```

This is possible because ArgumentParser's method `parse_args` accepts a list of strings as input for parsing.

### Changes to be introduced

A simple change on the behaviour of the `train` function should be enough, that is:

Option A:

rl_zoo3/train.py
```
import sys

def train(arguments_list: List[str] = sys.argv[1:]):
    ...
    args = parser.parse_args(arguments_list)
```

Option B:

rl_zoo3/train.py:
```
def train(arguments_list: List[str]):
    ...
    args = parser.parse_args(arguments_list)
``` 

train.py:
```
import sys
from rl_zoo3.train import train

if __name__ == "__main__":  # noqa: C901
    train(sys.argv[1:])
```

I'm more inclined to option B because it is much cleaner and straightforward to interpret what the program is doing.

### Change purpose
When using jupyter notebook and the program raises an exception, the magic line `%debug` is used to inspect the stack frame, executing `python train.py <args>` forces us to use another method to live debug.

### Final comments
All comments on why/why not the change should be done are always welcome.
Also comments on how to improve my current workflow are welcome. 
Let me know if I can proceed with the PR.

**Comment by araffin** [comment]
Hello,
you have actually a simple (slightly hacky solution), which allows you to do what you want:
```python
import sys
from rl_zoo3.train import train

sys.argv = ["python", "--algo", "ppo", "--env", "Pendulum-v1"]

train()
```

**Comment by richter43** [comment]
Tested and works flawlessly, much obliged! Should I close the issue? (I'm not very well versed on the the etiquette of GH issues)

**Comment by araffin** [comment]
> Should I close the issue? 

as it solves your issue, I would say so ;) (maybe later, I would appreciate a PR that add some documentation about that in the README ;))

**Comment by qgallouedec** [comment]
> Hello, you have actually a simple (slightly hacky solution), which allows you to do what you want:
> 
> ```python
> import sys
> from rl_zoo3.train import train
> 
> sys.argv = ["python", "--algo", "ppo", "--env", "Pendulum-v1"]
> 
> train()
> ```

It doesn't look very pythonic to me. I would recommend move argparsing in `rl-baselines3-zoo/train.py`.

Something like

`rl-baselines3-zoo/train.py`:
```python
import argparse

from rl_zoo3.train import train

if __name__ == "__main__":  # noqa: C901
    parser = argparse.ArgumentParser()
    parser.add_argument("--algo", help="RL Algorithm", default="ppo", type=str, required=False, choices=list(ALGOS.keys()))
    parser.add_argument("--env", type=str, default="CartPole-v1", help="environment ID")
    # [...]
    args = parser.parse_args()
    train(args.algo, args.env_id, ...)
```


`rl-baselines3-zoo/rl_zoo3/train.py`:
```python
from stable_baselines3.common.base_class import BaseAlgorithm

def train(algo: BaseAlgorithm, env_id: str, ...) -> None:
    # Everything currently in rl_zoo3.train.train, except argparsing
```

It would allow to import `train` from `rl_zoo3` and use it nicely:

```python
from stable_baselines3 import PPO
from rl_zoo3.train import train

train(PPO, "Pendulum-v0")
```

**Comment by richter43** [comment]
I'd agree with you on a whim if we were talking about any other library, but considering how the foundation of SB is Gym (Which in my opinion is one of the least Pythonic library) maybe we could give it a pass.

Besides this, the changes you propose aren't too hard to implement (A tad tedious, but doable).

**Comment by araffin** [comment]
so, different things: the zoo is not meant to be used from an interactive session (or only when debugging), if you need a more pythonic interface, you have the experiment manager and other utils available, or even SB3 api.
Making the rl zoo a package was mainly to give access to the wrappers/callbacks/utils, and to be able to call the train/enjoy scripts from anywhere.
I agree it's not pretty but that's only for debugging.
