### ISSUE TITLE
[Feature request] Load custom network classes from yaml file

### ISSUE THREAD

**Issue by Rick-v-E** [DLR-RM/rl-baselines3-zoo#300]
Stable baselines allows [custom network architectures](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#custom-network-architecture). It would be nice to be able to use these in RL Baselines3 Zoo as well. 

**Proposed change**
Adapt the hyperparam preprocessing function to load custom classes in the same way as it is done for callbacks. We can do this for every parameter key ending on `_class` when the parameter value contains a dot. 

This makes it possible to specify custom network architectures from the yaml files, e.g.:

```yaml
policy_kwargs:
    features_extractor_class: my_package.MyFeatureExtractor, 
```

Are you open to receive a pull request for this? Or is this too specific for my use-case?

**Comment by Rick-v-E** [comment]
Hello,
Thanks for your answer! Unfortunately that doesn't work, it raises:

```commandline
  File "/home/user/dlr_models/venv/lib/python3.9/site-packages/rl_zoo3/exp_manager.py", line 202, in setup_experiment
    model = ALGOS[self.algo](
  File "/home/user/dlr_models/venv/lib/python3.9/site-packages/stable_baselines3/dqn/dqn.py", line 103, in __init__
    super().__init__(
  File "/home/user/dlr_models/venv/lib/python3.9/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 111, in __init__
    super().__init__(
  File "/home/user/dlr_models/venv/lib/python3.9/site-packages/stable_baselines3/common/base_class.py", line 113, in __init__
    self.policy_class = self._get_policy_from_name(policy)
  File "/home/user/dlr_models/venv/lib/python3.9/site-packages/stable_baselines3/common/base_class.py", line 359, in _get_policy_from_name
    raise ValueError(f"Policy {policy_name} unknown")
ValueError: Policy my_package.MyCustomPolicyWithFeatureExtractor unknown
```
The reason is that the policy value in the `yaml` file is treated as a string. The package and class should be imported somewhere. Looking at the code, this can be achieved by adding some code to the `ExperimentManager`. I will open a pull request for this.

**Comment by araffin** [comment]
> The reason is that the policy value in the yaml file is treated as a string.

yes, I think it is also related to https://github.com/DLR-RM/stable-baselines3/issues/1126#issuecomment-1282280749 (see how to register custom policies)

**Comment by araffin** [comment]
closed by https://github.com/DLR-RM/rl-baselines3-zoo/pull/303

**Comment by araffin** [comment]
fyi, it is now possible to specify custom feature extractor using python config, see https://github.com/DLR-RM/rl-baselines3-zoo/pull/318
