### ISSUE TITLE
[Feature Request] Properly visually render panda_gym environments via enjoy.py without supplying env-kwargs

### ISSUE THREAD

**Issue by eric-y-chen** [DLR-RM/rl-baselines3-zoo#310]
### 🚀 Feature

As of 1.6.3 from PyPI, rendering of panda_gym 1.1.1 environments require env-kwargs `render:True` to be supplied to properly display the rendering during `enjoy` replay. If not supplied, no visualization appears and performance is still slowed as if it were rendering, i.e. not even functioning as if `--no-render` were supplied.

This request aligns the visualization behavior to match `mujoco-py`/`gym_robotics` and `pybullet` environments, like `FetchReach-v1` and `KukaBulletEnv-v0`, without having to supply `env-kwargs`.

### Pitch

Add the following snippet, or similar code, to `rl_zoo3/utils.py` in `create_test_env`:

```python
if ("panda_gym.envs" in str(gym.envs.registry.env_specs[env_id].entry_point)) and should_render:
    env_kwargs["render"] = True
```

The snippet was tested to ensure it produced the desired visualization behavior but was not regression tested to confirm whether it introduces bugs elsewhere.

---

Potentially add another `staticmethod` in `rl_zoo3/exp_manager.py` to handle panda_gym environments explicitly rather than simply `is_robotics_env` to make the above snippet more succinct.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo

**Comment by qgallouedec** [comment]
Thank you for spotting this.
LGTM, can you submit a PR?
