### ISSUE TITLE
[Bug]: Normalize=true in combination with image in HxWxC format crashes

### ISSUE THREAD

**Issue by Rick-v-E** [DLR-RM/rl-baselines3-zoo#312]
### 🐛 Bug

When using an image as state with format `HxWxC` in combination with the `normalize=True` hyperparameter, the training will crash. This is probably because the `VecNormalize` is applied before the `VecTransposeImage` in the experiment manager and the `VecNormalize` wrapper expects an input with format `CxWxH`.

### To Reproduce

Using an environment with a state with format `HxWxC`:

```python
import numpy as np

import gym


class TestEnv(gym.Env):
    def __init__(self) -> None:
        super().__init__()

        self.observation_space = gym.spaces.Box(0, 255, (60, 60, 3), dtype=np.uint8)
        self.action_space = gym.spaces.Discrete(5)

    def reset(self):
        obs = (np.random.rand(60, 60, 3) * 255).astype(np.uint8)
        return obs

    def step(self, action):
        obs = (np.random.rand(60, 60, 3) * 255).astype(np.uint8)
        return obs, 0.0, False, {}

```

And train this environment with `normalize=True`:

```shell
rl_zoo3 train --algo dqn --env test-v0 --hyperparams normalize:True
```

### Relevant log output / Error message

```shell
ValueError: could not broadcast input array from shape (12,60,60,3) into shape (12,3,60,60)
```

### System Info

Python: 3.8.10
Stable-Baselines3: 1.6.2
PyTorch: 1.13.0+cu117
GPU Enabled: True
Numpy: 1.23.4
Gym: 0.21.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo README](https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/README.md)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
do you want to normalize the image or only the reward?
for the image, the normalization is done already by SB3 (cf. doc), if you need to normalize part of the state keys only (when using dict observations), you can also do that (cf. doc again).

**Comment by Rick-v-E** [comment]
I was trying to normalize the reward. Therefore, I added:

```yaml
normalize: "{'norm_obs': False, 'norm_reward': True}"
```

to the yaml file, however, this crashes the training. 

However, the normalization done in SB3 is only dividing the image by 255 to have the values in [0, 1] right?

**Comment by Rick-v-E** [comment]
I am not sure where this crashes, however the order of `VecTransposeImage` and `VecNormalize` seems to be important:
```python
import numpy as np
import gym

from stable_baselines3 import DQN
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.vec_env import VecNormalize,  VecTransposeImage


class TestEnv(gym.Env):
    def __init__(self) -> None:
        super().__init__()

        self.observation_space = gym.spaces.Box(0, 255, (60, 60, 3), dtype=np.uint8)
        self.action_space = gym.spaces.Discrete(5)

    def reset(self):
        obs = (np.random.rand(60, 60, 3) * 255).astype(np.uint8)
        return obs

    def step(self, action):
        obs = (np.random.rand(60, 60, 3) * 255).astype(np.uint8)
        return obs, 0.0, False, {}


env_a = make_vec_env(TestEnv, n_envs=12)
env_a = VecTransposeImage(env_a)
env_a = VecNormalize(env_a, norm_obs=False)
env_a.reset()
print(env_a.step(np.zeros((12,)))[0].shape)

env_b = make_vec_env(TestEnv, n_envs=12)
env_b = VecNormalize(env_b, norm_obs=False)
env_b = VecTransposeImage(env_b)
env_b.reset()
print(env_b.step(np.zeros((12,)))[0].shape)

# Works
model = DQN("CnnPolicy", env_a)
model.learn(100)

# Crashes
model = DQN("CnnPolicy", env_b)
model.learn(100)
```

**Comment by araffin** [comment]
> to the yaml file, however, this crashes the training.

I guess this is the same as https://github.com/DLR-RM/stable-baselines3/issues/693, in the meantime, you can use the `vec_env_wrapper` argument to have the correct order.

A better fix would be in SB3 where we should call `get_original_obs()` only when `norm_obs=True`.

**Comment by Rick-v-E** [comment]
Thanks! Then I will use that key or reorder the images in my environment.
