### ISSUE TITLE
[Question] One-time evaluation score is not good indicator, and therefore probably should not be the tuning target?

### ISSUE THREAD

**Issue by lilin3336298** [DLR-RM/rl-baselines3-zoo#314]
### ❓ Question

I tried to train the agent with the tuned parameters from the best trial, but strangely, I found out the training cannot be as good as the reported score in the tuning process (actually, much worse). Anyone met this problem?

My guess for this problem is that the one-time evaluation is very stochastic (question: currently, sb3-rl-zoo is using one-time evaluation score as the target, right?). I think It is not a good measurement of how good the agent is.
Probably we should use the mean of multi-time evaluation scores as the tuning target, or using the mean reward from the rollout. What do you think? 
<img width="795" alt="evaluation not a good indicator" src="https://user-images.githubusercontent.com/9277720/202071544-3039c262-3342-4eab-8739-77e9a2c74329.png">
(for mountain car)

Thanks for any ideas!

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo README](https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/README.md)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Duplicate #204
Contributions are welcomed 🙂

**Comment by araffin** [comment]
Related to https://github.com/DLR-RM/rl-baselines3-zoo/issues/286 too.

In the meantime, you can also increase the number of evaluations episodes to reduce the noise (`--eval-episodes`).

> My guess for this problem is that the one-time evaluation is very stochastic (question: currently, sb3-rl-zoo is using one-time evaluation score as the target, right?).

not really, if you are using a pruner, it evaluates the agent periodically on several test episodes, but yes we current test only one seed.
To have hyperparameters that work for many random seeds, you can do a post-processing step (see https://github.com/DLR-RM/rl-baselines3-zoo/issues/151) or run multiple training (https://github.com/DLR-RM/rl-baselines3-zoo/issues/204).

**Comment by lilin3336298** [comment]
Thank you very much @araffin @qgallouedec. I learned a lot from your answers and from the related Q&A : )
