### ISSUE TITLE
[Feature Request] Custom feature extractor instead of the whole policy

### ISSUE THREAD

**Issue by whxru** [DLR-RM/rl-baselines3-zoo#316]
### 🚀 Feature

In SB3, users can customize the feature extractor solely by setting the sub-parameter `feature_extractor_class` and  `feature_extractor_kwargs` of the parameter `policy_kwargs`, which enables the separating customization of the feature extractor and the `net_arch` of the full-connected net. I noticed that recently support for using a custom policy was added, but with this feature, we can only customize the whole policy net. So I'm wondering can support for the aforementioned feature, i.e., the separate setting, be added to be consistent with the structure of SB3? 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo

**Comment by araffin** [comment]
Hello,
I guess you are referring to https://github.com/DLR-RM/rl-baselines3-zoo/issues/300
We actually discussed that with @ernestum and the correct way to do it would be allow `.py` instead of `.yaml` files.
Otherwise, you need a custom SB3 and rl_zoo3 version.

**Comment by whxru** [comment]
Thanks for your suggestion, I've implemented the whole network and it works well now.
