### ISSUE TITLE
[Question] Some hyperparameters still show in the output messages after commenting the code in hyperparams_opt.py

### ISSUE THREAD

**Issue by whxru** [DLR-RM/rl-baselines3-zoo#319]
### ❓ Question

I've deleted the whole key-value pair of "policy_kwargs" in the dict return of function `sample_ppo_params` in file `hyperparams_opt.py`, but the term 'net_arch' and 'activation_fn' still show in the trial report, e.g., 
```bash
Trial 366 finished with value: -2461672.8 and parameters: {'batch_size': 512, 'n_steps': 64, 'gamma': 0.98, 'learning_rate': 0.00024798451652281256, 'ent_coef': 7.186458520414247e-07, 'clip_range': 0.4, 'n_epochs': 5, 'gae_lambda': 0.99, 'max_grad_norm': 0.5, 'vf_coef': 0.576061254023277, 'net_arch': 'medium', 'activation_fn': 'relu'}. Best is trial 212 with value: -1970343.0.
```
I tried to locate the problem in a bottom-up manner from the code which outputs this message, but I didn't find according lines (I guess this message is outputted directly by Optuna).

So is this a bug or just due to the incorrect way that I tried to eliminate the `net_arch` and `activation_fn` from the tuning space? Does the existence of the two terms in the output message mean that they are actually set?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo README](https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/README.md)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
I bet you commented these lines after running the first trial of your study. If so,then this output is expected: you can't modify optuna optimizable values after initializing the study.
Create a new study would solve this, but you would lost the benefit of all your past trials.

**Comment by whxru** [comment]
@qgallouedec Hi, thanks for your reply. I found that the correct way to remove these parameters is to comment both lines in the return dict AND lines like `trail.suggest_categorical(...)` (which I didn't comment).
