### ISSUE TITLE
[Bug]: TypeError: __init__() got an unexpected keyword argument 'n_epochs'

### ISSUE THREAD

**Issue by qgallouedec** [DLR-RM/rl-baselines3-zoo#327]
### 🐛 Bug

Got the following error.

### To Reproduce

```shell
 python train.py --algo trpo --env InvertedPendulumSwingupBulletEnv-v0
```

### Relevant log output / Error message

```shell
========== InvertedPendulumSwingupBulletEnv-v0 ==========
Seed: 1304407939
Loading hyperparameters from: /gpfsdswork/projects/rech/uli/upf82sp/rl-baselines3-zoo/hyperparams/trpo.yml
Default hyperparameters for environment (ones being tuned will be overridden):
OrderedDict([('batch_size', 64),
             ('gae_lambda', 0.95),
             ('gamma', 0.99),
             ('learning_rate', 0.00025),
             ('n_envs', 8),
             ('n_epochs', 10),
             ('n_steps', 2048),
             ('n_timesteps', 2000000.0),
             ('normalize', True),
             ('policy', 'MlpPolicy')])
Using 8 environments
Creating test environment
pybullet build time: May 20 2022 19:45:31
Normalization activated: {'gamma': 0.99, 'norm_reward': False, 'training': False}
Normalization activated: {'gamma': 0.99}
Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/uli/upf82sp/rl-baselines3-zoo/train.py", line 4, in <module>
    train()
  File "/gpfsdswork/projects/rech/uli/upf82sp/rl-baselines3-zoo/rl_zoo3/train.py", line 259, in train
    results = exp_manager.setup_experiment()
  File "/gpfsdswork/projects/rech/uli/upf82sp/rl-baselines3-zoo/rl_zoo3/exp_manager.py", line 204, in setup_experiment
    model = ALGOS[self.algo](
TypeError: __init__() got an unexpected keyword argument 'n_epochs'
```

### System Info

OS: Linux-4.18.0-305.65.1.el8_4.x86_64-x86_64-with-glibc2.28 #1 SMP Thu Sep 22 08:28:21 EDT 2022
Python: 3.9.12
Stable-Baselines3: 1.6.2
PyTorch: 1.13.0+cu117
GPU Enabled: False
Numpy: 1.23.5
Gym: 0.21.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo README](https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/README.md)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Oh, I see, that's the "to be tuned" parameters that are copied from PPO.
