### ISSUE TITLE
[Question] How to get the features extracted by cnn

### ISSUE THREAD

**Issue by 1176358062** [DLR-RM/rl-baselines3-zoo#333]
### ❓ Question

Now the great thing about this code base is that the feature extraction layer and the action output layer can be defined separately.
So, is it possible to specify to obtain the output of the feature extraction layer instead of the output of the action output layer when obtaining the model output?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo README](https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/README.md)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
```python
import torch

from stable_baselines3 import PPO

# Build model
model = PPO("MlpPolicy", "CartPole-v1")

# Whatever vectorized observation
obs = model.env.observation_space.sample()
obs = torch.tensor(obs).unsqueeze(0)

# Extract features
features = model.policy.features_extractor(obs)
```

**Comment by 1176358062** [comment]
> ```python
> import torch
> 
> from stable_baselines3 import PPO
> 
> # Build model
> model = PPO("MlpPolicy", "CartPole-v1")
> 
> # Whatever vectorized observation
> obs = model.env.observation_space.sample()
> obs = torch.tensor(obs).unsqueeze(0)
> 
> # Extract features
> features = model.policy.features_extractor(obs)
> ```

Thanks!
