### ISSUE TITLE
[Bug]: wrong optuna_eval_freq

### ISSUE THREAD

**Issue by qihuazhong** [DLR-RM/rl-baselines3-zoo#346]
### 🐛 Bug

I noticed that after specifying ` --n-eval-envs 10` in my h.params tuning, the pruner is not pruning anything. After some digging, the culprit is probably the wrong optuna_eval_freq.

in `ExperimentManager.objective()`:
```python
eval_env = self.create_envs(n_envs=self.n_eval_envs, eval_env=True)

optuna_eval_freq = int(self.n_timesteps / self.n_evaluations)
# Account for parallel envs
optuna_eval_freq = max(optuna_eval_freq // self.n_envs, 1)
```

The last line should probably be 
```python
optuna_eval_freq = max(optuna_eval_freq // self.n_eval_envs, 1)
```
since `self.n_eval_envs`  is not always the same as `self.n_envs`

I could submit a PR if this is agreed on.

### To Reproduce

```shell
python train.py --algo dqn --env "customenv-v0" -optimize --n-trials 200 --n-eval-envs 10 --eval-episodes 100  --n-jobs 8 --n-evaluations 20 --sampler tpe --pruner median
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo README](https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/README.md)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> The last line should probably be

the line looks correct (cf. doc). The number of evaluation environments should not influence how often we evaluate.
