### ISSUE TITLE
[Bug]: bug title

### ISSUE THREAD

**Issue by Delta-Ark** [DLR-RM/rl-baselines3-zoo#349]
### 🐛 Bug

When I run ppo asteroids the video I think only shows 1/3 of the screen. I'm running the default colab in the github. 

### To Reproduce

```shell
python train.py --algo ...
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo README](https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/README.md)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
I close this issue because it is inactive and the information provided are not sufficient to describe the problem.
