### ISSUE TITLE
`HumanoidStandup-v3`, `Reacher-v3` and `Inverted[Double]Pendulum-v3` not found in gym registry

### ISSUE THREAD

**Issue by qgallouedec** [DLR-RM/rl-baselines3-zoo#350]
### 🐛 Bug

Probably a mistake in #183, HumanoidStandup was not part of the mujoco migration v2 -> v3, see https://github.com/openai/gym/pull/1304/

### To Reproduce

```shell
python train.py --algo pro --env HumanoidStandup-v3
```

### Relevant log output / Error message

```shell
Traceback (most recent call last):
  File "/Users/quentingallouedec/rl-baselines3-zoo/train.py", line 4, in <module>
    train()
  File "/Users/quentingallouedec/rl-baselines3-zoo/rl_zoo3/train.py", line 180, in train
    raise ValueError(f"{env_id} not found in gym registry, you maybe meant {closest_match}?")
ValueError: HumanoidStandup-v3 not found in gym registry, you maybe meant HumanoidStandup-v2?
```

### System Info

- OS: macOS-13.1-arm64-arm-64bit Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103
- Python: 3.9.16
- Stable-Baselines3: 1.8.0a2
- PyTorch: 1.12.0
- GPU Enabled: False
- Numpy: 1.23.1
- Gym: 0.21.0
- Mujoco: 2.3.1.post1
- Mujoco-py: 2.1.2.14

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo README](https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/README.md)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> Probably a mistake in https://github.com/DLR-RM/rl-baselines3-zoo/pull/183, H

does the v4 exist?
if so, I would switch to v2 for now and when we move to gymnasium, switch everything to v4 (this will use the new mujoco bindings, which are also easier to install).

**Comment by qgallouedec** [comment]
v4 was introduced in gym 0.24
Same problem for reacher btw
