### ISSUE TITLE
[Feature Request] `n_envs` as a train argument

### ISSUE THREAD

**Issue by qgallouedec** [DLR-RM/rl-baselines3-zoo#356]
### 🚀 Feature

It could be great to have an `n_envs` arg in train.

```sh
python -m rl_zoo3 --algo ppo --env CartPole-v1 --n-envs 8
```

### Motivation

Currently, the only way to set the number of env is modifying the config file.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo

**Comment by araffin** [comment]
> Currently, the only way to set the number of env is modifying the config file.

`-params n_envs:8` should do the job ;)
