### ISSUE TITLE
Cloudpickle dependency issue

### ISSUE THREAD

**Issue by hawxkeye** [DLR-RM/rl-baselines3-zoo#358]
I had cloudpickle v1.6.0 installed with Python3.11 and could not run SubProcVec environments anymore.
While stable-baselines3 requires cloudpickle, rl_zoo requires a cloudpickle version >= 1.5.0

I think the issue is, that rl_zoo and sb3 both support Python3.7+, while cloudpickle only supports Python3.11 from version 2.1.0
To support newer version of Python, the minimum version requirement of cloudpickle in the requirements.txt should be increased.
Please feel free to discuss! For me, all my sb3 agents broke down after using rl_zoo, and using the most recent cloudpickle version in sb3 solved this issue. One could also argue, that sb3 should require a high enough version.

**Comment by araffin** [comment]
Hello,
I'm not sure to follow.
In short, with which versions (python and cloudpickle) did you train your agents?
and with with version did you try to load them?

Incompatibilities between cloudpickle versions and python versions is a known issue: https://stable-baselines3.readthedocs.io/en/master/guide/save_format.html

> To support newer version of Python, the minimum version requirement of cloudpickle in the requirements.txt should be increased.

` cloudpickle version >= 1.5.0`  allows cloudpickle 2.0+, I'm not sure to follow why this is a restriction.

**Comment by hawxkeye** [comment]
Hi, sorry for the unclear description.
I did not actually start learning or loading models. The call to make_vec_env with 'SubProcVec' as input parameter fails immediately when using cloudpickle 1.6.0
The problem comes from switching between both project. 
If you, e.g., install cloudpickle 1.6.0, dependencies for sb3 and rl_zoo are fulfilled. 
However, the make_vec_env call fails, due to a cloudpickle issue.
To solve this, you can install cloudpickle 2.0+, and make_vec_env will run again.
I did everything with Python3.11

So the reason of opening the issue, is simply to make you aware, that combinations of using Python3.7+ and cloudpickle>=1.5.0 do not actually work anymore.
So, from my POV, increasing the version of cloudpickle could solve this, however I am not sure if there are side effects.

**Comment by araffin** [comment]
> I did not actually start learning or loading models. The call to make_vec_env with 'SubProcVec' as input parameter fails immediately when using cloudpickle 1.6.0

Could you please fill the issue template and provide minimal code to reproduce the error + traceback? (formatted using markdown code-block).

**Comment by hawxkeye** [comment]
## Minimum code to reproduce
```
import gym

from stable_baselines3 import A2C
from stable_baselines3.common.vec_env import SubprocVecEnv, DummyVecEnv
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.utils import set_random_seed

def make_env(env_id, rank, seed=0):
    """
    Utility function for multiprocessed env.

    :param env_id: (str) the environment ID
    :param num_env: (int) the number of environments you wish to have in subprocesses
    :param seed: (int) the inital seed for RNG
    :param rank: (int) index of the subprocess
    """
    def _init():
        env = gym.make(env_id)
        env.seed(seed + rank)
        return env
    set_random_seed(seed)
    return _init


if __name__ == "__main__":
    env_id = "CartPole-v1"
    num_cpu = 4  # Number of processes to use
    env = SubprocVecEnv([make_env(env_id, i) for i in range(num_cpu)])

    model = A2C("MlpPolicy", env, verbose=1)
    model.learn(total_timesteps=10_000)
```
## Code runs with
Python3.11
Cloudpickle 2.2.1

## Code does fails with
Python3.11
Cloudpickle 1.6.0 (Versions <2.1.0)

## Traceback when failing
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/forkserver.py", line 274, in main
    code = _serve_one(child_r, fds,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/forkserver.py", line 313, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 130, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeuserlocal/lib/python3.11/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 375, in __setstate__
    self.var = cloudpickle.loads(var)
               ^^^^^^^^^^^^^^^^^^^^^^
TypeError: code() argument 13 must be str, not int
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/forkserver.py", line 274, in main
    code = _serve_one(child_r, fds,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/forkserver.py", line 313, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 130, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 375, in __setstate__
    self.var = cloudpickle.loads(var)
               ^^^^^^^^^^^^^^^^^^^^^^
TypeError: code() argument 13 must be str, not int
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/forkserver.py", line 274, in main
    code = _serve_one(child_r, fds,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/forkserver.py", line 313, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 130, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 375, in __setstate__
    self.var = cloudpickle.loads(var)
               ^^^^^^^^^^^^^^^^^^^^^^
TypeError: code() argument 13 must be str, not int
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/forkserver.py", line 274, in main
Traceback (most recent call last):
  File "/home/user/test.py", line 28, in <module>
    code = _serve_one(child_r, fds,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/forkserver.py", line 313, in _serve_one
    env = SubprocVecEnv([make_env(env_id, i) for i in range(num_cpu)])
    code = spawn._main(child_r, parent_sentinel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 130, in _main
  File "/home/user/.local/lib/python3.11/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 112, in __init__
    self = reduction.pickle.load(from_parent)
    observation_space, action_space = self.remotes[0].recv()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 375, in __setstate__
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 249, in recv
    buf = self._recv_bytes()
    self.var = cloudpickle.loads(var)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 413, in _recv_bytes
               ^^^^^^^^^^^^^^^^^^^^^^
TypeError: code() argument 13 must be str, not int
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 378, in _recv
    chunk = read(handle, remaining)
            ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
```

## Comments
Cloudpickle started to support Python3.11 with Version 2.1.0 (according to [Cloudpickle CHANGES](https://github.com/cloudpipe/cloudpickle/blob/master/CHANGES.md))
Therefore, a combination of Python3.7+ and Cloudpickle>=1.5.0 does not run, which are currently the requirements of the rl_zoo
Sorry, I did not find the issue template :)

**Comment by araffin** [comment]
sounds more like an issue from cloudpickle (the tags used are not the good ones looking at https://pypi.org/project/cloudpickle/)

> Therefore, a combination of Python3.7+ and Cloudpickle>=1.5.0 does not run

well, only python 3.11, no?
I'm also wondering why pip would download cloudpickle 1.6.0 when `Cloudpickle>=1.5.0` is specified (normally, it should download the latest version).
we can probably add a condition to download cloudpickle >= 2.1.0 if python 3.11 is used.
