### ISSUE TITLE
[Question] The actual training timesteps don't correspond with the hyper-parameters for Atari

### ISSUE THREAD

**Issue by cx441000319** [DLR-RM/rl-baselines3-zoo#367]
### ❓ Question

Hi,

As the title says, it seems the issue only occurs in Atari. Here are some commands and images for reference:

**Experiment Command:**
python train.py --algo ppo --env PongNoFrameskip-v4
![image](https://user-images.githubusercontent.com/105121907/224877354-9f57d416-c27d-4f01-a3bc-74708bbc6d6a.png)

**Training Plotting Command:**
python scripts/plot_train.py -a ppo -e PongNoFrameskip-v4 -f logs
![image](https://user-images.githubusercontent.com/105121907/224877631-f5064409-91e9-4925-83a4-898420a001b4.png)

**Evaluation Plotting Command:**
python scripts/all_plots.py -a ppo -e PongNoFrameskip-v4 -f logs --no-million -max 10000000
![image](https://user-images.githubusercontent.com/105121907/224877601-148e7ed5-b7ad-464d-8eb7-dc916de17186.png)

We can tell the number of the training timesteps is about **4e7** instead of **1e7** (**n_timesteps** in the hyper-parameters). The issue doesn't exist in the environments except for Atari based on my experiment results. If you want to reproduce the same issue, you can simply replace the hyper-parameter n_timesteps with a small number like 1e4 and you will find there are much more than 1e4 samples according to the episodic lengths in the logs.

Thank you so much in advance!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo documentation](https://rl-baselines3-zoo.readthedocs.io)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
this is expected because of preprocessing for Atari games (the action repeat, aka frameskip, is set to 4 by default.

Relatee: https://github.com/DLR-RM/stable-baselines3/issues/181

**Comment by cx441000319** [comment]
Oh, that totally makes sense. I tried my best to check if there were any details I ignored, but I didn't realize it before. It's all clear now. Thank you so much for your quick reply!
