### ISSUE TITLE
[Question] full_action_space not working as expected

### ISSUE THREAD

**Issue by Bleyddyn** [DLR-RM/rl-baselines3-zoo#375]
### ❓ Question

I'm attempting to train a single model on two environments. Because they have different action spaces, I set full_action_space to True, but I'm still getting an error showing that the model does not have the full action space.

```
python3 rl-baselines3-zoo/train.py --algo ppo --env "PongNoFrameskip-v4" --progress --tensorboard-log ./logs/zoo/ppo_pong --eval-freq 100000 --eval-episodes 10 --n-eval-envs 1 --save-freq 100000 --env-kwargs "full_action_space:True"

python3 -m rl_zoo3.benchmark --log-dir rl-trained-agents --benchmark-dir benchmarks --no-hub --n-timesteps 100000

python3 rl-baselines3-zoo/train.py --algo ppo --env "BreakoutNoFrameskip-v4" -i rl-trained-agents/ppo/PongNoFrameskip-v4_1/PongNoFrameskip-v4.zip --progress --tensorboard-log ./logs/zoo/ppo_breakout --eval-freq 100000 --eval-episodes 10 --n-eval-envs 1 --save-freq 100000 --env-kwargs "full_action_space:True"

========== BreakoutNoFrameskip-v4 ==========
Seed: 4265367534
Loading hyperparameters from: /Users/Shared/monitor/rl-baselines3-zoo/hyperparams/ppo.yml
Default hyperparameters for environment (ones being tuned will be overridden):
OrderedDict([('batch_size', 256),
             ('clip_range', 'lin_0.1'),
             ('ent_coef', 0.01),
             ('env_wrapper',
              ['stable_baselines3.common.atari_wrappers.AtariWrapper']),
             ('frame_stack', 4),
             ('learning_rate', 'lin_2.5e-4'),
             ('n_envs', 8),
             ('n_epochs', 4),
             ('n_steps', 128),
             ('n_timesteps', 10000000.0),
             ('policy', 'CnnPolicy'),
             ('vf_coef', 0.5)])
Using 8 environments
Creating test environment
A.L.E: Arcade Learning Environment (version 0.8.1+53f58b7)
[Powered by Stella]
Stacking 4 frames
Wrapping the env in a VecTransposeImage.
Stacking 4 frames
Wrapping the env in a VecTransposeImage.
Loading pretrained agent
~/Library/Python/3.11/lib/python/site-packages/stable_baselines3/common/save_util.py:166: UserWarning: Could not deserialize object learning_rate. Consider using `custom_objects` argument to replace this object.
Exception: code expected at least 16 arguments, got 15
  warnings.warn(
~/Library/Python/3.11/lib/python/site-packages/stable_baselines3/common/save_util.py:166: UserWarning: Could not deserialize object lr_schedule. Consider using `custom_objects` argument to replace this object.
Exception: code expected at least 16 arguments, got 15
  warnings.warn(
~/Library/Python/3.11/lib/python/site-packages/stable_baselines3/common/save_util.py:166: UserWarning: Could not deserialize object clip_range. Consider using `custom_objects` argument to replace this object.
Exception: code expected at least 16 arguments, got 15
  warnings.warn(
~/Library/Python/3.11/lib/python/site-packages/stable_baselines3/common/vec_env/patch_gym.py:95: UserWarning: You loaded a model that was trained using OpenAI Gym. We strongly recommend transitioning to Gymnasium by saving that model again.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/Shared/monitor/rl-baselines3-zoo/train.py", line 4, in <module>
    train()
  File "/Users/Shared/monitor/rl-baselines3-zoo/rl_zoo3/train.py", line 256, in train
    results = exp_manager.setup_experiment()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Shared/monitor/rl-baselines3-zoo/rl_zoo3/exp_manager.py", line 200, in setup_experiment
    model = self._load_pretrained_agent(self._hyperparams, env)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Shared/monitor/rl-baselines3-zoo/rl_zoo3/exp_manager.py", line 680, in _load_pretrained_agent
    model = ALGOS[self.algo].load(
            ^^^^^^^^^^^^^^^^^^^^^^
  File "~/Library/Python/3.11/lib/python/site-packages/stable_baselines3/common/base_class.py", line 716, in load
    check_for_correct_spaces(env, data["observation_space"], data["action_space"])
  File "~/Library/Python/3.11/lib/python/site-packages/stable_baselines3/common/utils.py", line 232, in check_for_correct_spaces
    raise ValueError(f"Action spaces do not match: {action_space} != {env.action_space}")
ValueError: Action spaces do not match: Discrete(6) != Discrete(18)
```
Versions
stable-baselines3             2.0.0a5
rl-zoo3                       2.0.0a4
gymnasium                     0.28.1
torch                         2.0.0
Python 3.11.3

Results from the benchmark run showing that training worked:

algo | env_id | mean_reward | std_reward | n_timesteps | eval_timesteps | eval_episodes
-- | -- | -- | -- | -- | -- | --
ppo | PongNoFrameskip-v4 | 20.917 | 0.526 | 10M | 400740 | 60

Two odd things:

I do have gym v0.26.2 installed, although I'm not intentionally using it, so I'm not sure why the training script would have trained the Pong model using it. "You loaded a model that was trained using OpenAI Gym"

The model's action space is Discrete(6), which would be valid for Pong if full_action_space had not been set to True.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo documentation](https://rl-baselines3-zoo.readthedocs.io)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,

> i rl-trained-agents/ppo/PongNoFrameskip-v4_1/PongNoFrameskip-v4.zip

it looks like you are trying to load a pre-trained model from the RL Zoo.
Those models were trained using gym 0.21 (or anterior) with limited action space, so the error looks normal.
You cannot change the action space at test time (that what the error tells you).

In order to do what you want, you would need to use a model pre-trained using full action space.

**Comment by Bleyddyn** [comment]
I have two different rl-trained-agents directories. One inside the rl-baselines3-zoo repository and one outside. The one I was attempting to retrain was a model I had trained (using the first call in the code I included) a few days ago.

Is there some way I can manually load a trained model and show its structure, specifically the number of outputs in the top layer?

**Comment by araffin** [comment]
A minimal example for what you want to do:

1. Train a PPO agent on Pong from scratch:
```
python3 -m rl_zoo3.train --algo ppo --env PongNoFrameskip-v4 -f pong --env-kwargs "full_action_space:True" -n 5000
```

2. Train a PPO agent on Breakout starting from the Pong agent:
```
python3 -m rl_zoo3.train --algo ppo --env BreakoutNoFrameskip-v4 -f breakout --env-kwargs "full_action_space:True" -n 5000 -i pong/ppo/PongNoFrameskip-v4_1/PongNoFrameskip-v4.zip
```

> Is there some way I can manually load a trained model and show its structure, specifically the number of outputs in the top layer?

probably yes but it will require custom code.


Note: those commands works from any folder as long you have RL Zoo installed.

**Comment by Bleyddyn** [comment]
Thanks, that worked. I still can't see how mine was different, but I'll re-run everything with clearer directory names.
