### ISSUE TITLE
[Question] No module named 'ae' when running train.py 

### ISSUE THREAD

**Issue by Guosy0506** [DLR-RM/rl-baselines3-zoo#377]
### ❓ Question

I want to use SAC in CarRacing-V2, and when I typing "python train.py --algo sac --env CarRacing-v2", I got the Error be like:
![image](https://github.com/DLR-RM/rl-baselines3-zoo/assets/86408789/ae6484a6-be6d-43aa-b443-55ca31d7c4b9)

how can I deal it?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo documentation](https://rl-baselines3-zoo.readthedocs.io)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
if you look at the config:https://github.com/DLR-RM/rl-baselines3-zoo/blob/382dcabbd9815cb9557503a7caa0c54a562fa7fb/hyperparams/sac.yml#L168

It comes from this video serie: https://m.youtube.com/playlist?list=PL42jkf1t1F7dFXE7f0VTeFLhW0ZEQ4XJV
