### ISSUE TITLE
[Bug]: TypeError: 'EnvRegistry' object is not iterable

### ISSUE THREAD

**Issue by Melanol** [DLR-RM/rl-baselines3-zoo#381]
### 🐛 Bug

I get this error after pulling the latest commit in master (spent almost a year without touching the zoo) and running
```shell
python enjoy.py --algo a2c --env BreakoutNoFrameskip-v4 --folder rl-trained-agents/ -n 5000
```
I also think requirements.txt needs to be updated.

### To Reproduce

```shell
python enjoy.py --algo a2c --env BreakoutNoFrameskip-v4 --folder rl-trained-agents/ -n 5000
```

### Relevant log output / Error message

```shell
Traceback (most recent call last):
  File "/home/mel/PycharmProjects/rl-baselines3-zoo/enjoy.py", line 1, in <module>
    from rl_zoo3.enjoy import enjoy
  File "/home/mel/PycharmProjects/rl-baselines3-zoo/rl_zoo3/__init__.py", line 6, in <module>
    import rl_zoo3.gym_patches  # noqa: F401
  File "/home/mel/PycharmProjects/rl-baselines3-zoo/rl_zoo3/gym_patches.py", line 82, in <module>
    patched_registry.update(gym.envs.registration.registry)
TypeError: 'EnvRegistry' object is not iterable
```

### System Info

- OS: Linux-5.19.0-43-generic-x86_64-with-glibc2.35 # 44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2
- Python: 3.10.11
- Stable-Baselines3: 1.8.0
- PyTorch: 2.0.1+cu117
- GPU Enabled: True
- Numpy: 1.24.3
- Gym: 0.21.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo documentation](https://rl-baselines3-zoo.readthedocs.io)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> I also think requirements.txt needs to be updated.

The requirements are updated, for RL Zoo master version, SB3 2.x is required and gym 0.21 is no longer supported (gymnasium is the new backend and gym 0.26 is also supported).

https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/requirements.txt#L1-L3

**Comment by Melanol** [comment]
> SB3 2.x is required

When I run 'pip install stable-baselines3[extra_no_roms,tests,docs]>=2.0.0a9', I get no output. Could it be because I am in Russia?

**Comment by Melanol** [comment]
I tried `pip install stable-baselines3[extra_no_roms,tests,docs]>=2.0.0a9` and got
```shell
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Seems like gym/gymnasium broke stable-baselines.
