### ISSUE TITLE
[Question] Correct way of hyper parameter optimization for new algorithm?

### ISSUE THREAD

**Issue by tyler-ingebrand** [DLR-RM/rl-baselines3-zoo#384]
### ❓ Question

Hello,

I am writing a new algorithm based on the sb3 implementation of PPO. However, I need to run hyper parameter optimization since I changed some parts of the algorithm and the defaults no longer work for me. What is the best way to test a new algorithm, which implements BasePolicy, using this package? Do I need to just clone the repo and modify utils.py, hyperparams_opt.py, etc? Or is there a cleaner way? 

Thank you for your time

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo documentation](https://rl-baselines3-zoo.readthedocs.io)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
yes, a fork would be the way to go.
If you just want to add/replace an algorithm, you can take a look at https://rl-baselines3-zoo.readthedocs.io/en/master/guide/sbx.html
