### ISSUE TITLE
[Feature Request] Outdated dockerfile

### ISSUE THREAD

**Issue by VineetTambe** [DLR-RM/rl-baselines3-zoo#391]
### 🚀 Feature

Hey, 

I was trying to use the docker setup in the stablebaselines3 docker setup. But it seems to be really outdated in terms of the base image version? 

### Motivation

In addition to it being outdated. I am kind of confused as to why a run_gpu.sh and run_cpu.sh scripts are used as opposed to a docker compose? Which is a much cleaner way of doing the same? 

### Pitch

I went ahead and created an up to date dockerfile with gpu support with `stable-baselines3==2.0.0a13`.
It has docker-compose support as well. 
Should I go ahead and raise a PR for it? 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo

**Comment by araffin** [comment]
Hello,

> I was trying to use the docker setup in the stablebaselines3 docker setup. But it seems to be really outdated in terms of the base image version?

Are you talking about the dockerfile or the image found on dockerhub?

The dockerfile should be up to date (I moved to micromamba recently), but because of new docker restrictions, I wasn't motivated to keep dockerhub versions up to date...

**Comment by VineetTambe** [comment]
Hey @araffin ,

I was talking about the image found on the dockerhub as the dockerfile pulls that image and a bunch of packages in the base image are outdated.
