### ISSUE TITLE
[Feature Request] Remove gym dependency

### ISSUE THREAD

**Issue by ernestum** [DLR-RM/rl-baselines3-zoo#398]
### 🚀 Feature

Remove gym dependency.

### Motivation

I think we don't need gym support any more and it clutters our dependencies.

### Pitch

- Remove the dependency from `requirements.txt` and `setup.py`.
- Remove the gym-specific sections in the `gym_patches.py` file.

### Alternatives

Keep it in because we still need it for some reason.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo

**Comment by araffin** [comment]
> Ah but for that there is not pypi release yet?

There is but I also need to push the latest version (https://pypi.org/project/pybullet-envs-gymnasium/), I will give you access to pypi when I'm home.
