### ISSUE TITLE
How to run hyperparameter tuning with multiple seeds for each configuration?

### ISSUE THREAD

**Issue by alexlioralexli** [DLR-RM/rl-baselines3-zoo#40]
Unless I'm missing something, hyperparameter tuning just runs each config with a single seed, which makes it difficult to draw conclusions for research due to stochasticity. Is there any way to do tuning with a consistent set of seeds and average results over 3-5 runs?

**Comment by araffin** [comment]
>Is there any way to do tuning with a consistent set of seeds and average results over 3-5 runs?

yes, you need to change the objective function: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/utils/hyperparams_opt.py#L89

and the callback.

But it is not recommended as it well take much more time.

**Comment by araffin** [comment]
closing in favor of https://github.com/DLR-RM/rl-baselines3-zoo/issues/151
