### ISSUE TITLE
[Feature Request] Specify custom keyword arguments for eval environments

### ISSUE THREAD

**Issue by Quentin18** [DLR-RM/rl-baselines3-zoo#404]
### 🚀 Feature

Add the `--eval-env-kwargs` parameter to the `train.py` script in order to specify keyword arguments to pass to the env constructor for evaluation.

### Motivation

Actually, we cannot specify different keyword arguments between training and evaluation environments. It can be usefull if we want  the evaluation environment to behave differently from the training one.

### Additional context

You can see the usage in this [commit](https://github.com/Quentin18/rl-baselines3-zoo/commit/63f9b09df9cd03cc672066930d1f354cf48778d4).

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo

**Comment by araffin** [comment]
Hello,
Sounds like a good to have feature, i would be happy to receive a PR for it =) (the default should remain the same though)

**Comment by Quentin18** [comment]
Hello,
OK thanks :ok_hand: ! Here is the PR : https://github.com/DLR-RM/rl-baselines3-zoo/pull/405
