### ISSUE TITLE
Plotting Script Improvement 

### ISSUE THREAD

**Issue by VinayHajare** [DLR-RM/rl-baselines3-zoo#413]
### 📚 Documentation

The 'Plotting Script' section under the 'Integration' has some grammatical mistake in readme.md file of the main repository.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo

**Comment by araffin** [comment]
Hello,
for those kind of improvements, you can directly open a PR =)
