### ISSUE TITLE
[Question] How many startup trials in distributed optimization

### ISSUE THREAD

**Issue by mzelazko** [DLR-RM/rl-baselines3-zoo#450]
### ❓ Question

I'm distributing optimization across 6 processes.
I know if I use for each of 6 processes `--n-trials 100` then i will get 600 trials.
But what with `--n-startup-trials 10`? Will there be 10 or 60 startup trials? 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo documentation](https://rl-baselines3-zoo.readthedocs.io)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> hen i will get 600 trials.

correct.

> Will there be 10 or 60 startup trials?

I'm not sure about that one, but I would assume `10` if you use a database.
I also would say it's more an optuna question than a RL Zoo one.

**Comment by mzelazko** [comment]
I have used database indeed.
I added print function next to random sampler and it appeard that the answer is 10 startup trials for 6 processes on `--n-startup-trials 10` .
Thank you for answer.
