### ISSUE TITLE
[Question] Should train & eval environment seeds differ?

### ISSUE THREAD

**Issue by leokraft** [DLR-RM/rl-baselines3-zoo#459]
### ❓ Question

First of all, thank you for the wonderful project!

I have a question about the random seed used for creating environments. It appears the same seed is used for both training and evaluation environments (see [here](https://github.com/DLR-RM/rl-baselines3-zoo/blob/27e081eb24419ee843ae1c329b0482db823c9fc1/rl_zoo3/exp_manager.py#L622)).

Is it not a problem to use the same seed for both training and evaluation?
Intuitively, I would expect different seeds to be used.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo documentation](https://rl-baselines3-zoo.readthedocs.io)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
No, it's not a problem. The initial shared seed doesn't cause correlation between training and evaluation data. The state of the environment (including the rng state) depends not only on the seed but also on all the actions taken, and things like how many times you've sampled from the action space etc. As soon as any change occurs, even a small one, the environments become completely uncorrelated.

I hope I've been clear, I've gone over it several times to formulate this, if anyone has a clearer formulation I'm a taker :sweat_smile:.

**Comment by qgallouedec** [comment]
Maybe for the very first episode of the first evaluating agent, but not for the rest. That said, Frozen Lake is not a good example because the holes are not randomised.

**Comment by leokraft** [comment]
Got it!
Thank you for all the insightful comments.
