### ISSUE TITLE
[Question] branch 'feat/recurrent-ppo' disappeared

### ISSUE THREAD

**Issue by chenyangkang** [DLR-RM/rl-baselines3-zoo#471]
### ❓ Question

Hi! I was reading [this doc](https://sb3-contrib.readthedocs.io/en/master/modules/ppo_recurrent.html#how-to-replicate-the-results) and [this blog](https://wandb.ai/sb3/no-vel-envs/reports/PPO-vs-RecurrentPPO-aka-PPO-LSTM-on-environments-with-masked-velocity-SB3-Contrib---VmlldzoxOTI4NjE4) which give evaluation to the recurrentPPO in the sb3_contrib package. They said the code for reproduce the result is in the `feat/recurrent-ppo` branch of this repo. But I can't find it. Could anyone inform why? Thank you!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo documentation](https://rl-baselines3-zoo.readthedocs.io)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
my bad, you either use the latest version of RL Zoo or commit `139477b3345f36042c28fe06735406` (see https://github.com/DLR-RM/rl-baselines3-zoo/pull/190).
