### ISSUE TITLE
Releasing parts of this repo as a PyPi package for hyperparameter tuning [Enhancement]

### ISSUE THREAD

**Issue by mlap** [DLR-RM/rl-baselines3-zoo#53]
Hi all,

First, I'd like to say thank you to all the contributors on this repo as well as on stable baselines. I have used both extensively in my own research and appreciate the effort that you all have made here. 

I have been using this repo to do hyperparameter tuning on my own environments with stable baslines 3. I primarily just copy `train.py` and `utils/` to my own directory and go from there. But since you all make continual improvements to this library, I was wondering if it would be possible to wrap up some of the files here as a PyPi package so that users that want to do hyperparameter tuning with this repo could easily install the appropriate files, use them and keep them up to date. I imagine that this would be very helpful for all regular users of stable baselines -- and perhaps this is something that would be better off integrated in the next stable baselines 3 release.

**Comment by araffin** [comment]
Hello,

I think your request is close to https://github.com/araffin/rl-baselines-zoo/issues/107 .
The good news for you is that I plan to migrate most of rl-zoo utils (wrappers, callbacks) to our new [SB3 Contrib](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib) repo.

Associated issue: https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/3

**Comment by araffin** [comment]
now done in https://github.com/DLR-RM/rl-baselines3-zoo/releases
