### ISSUE TITLE
[question] Hyperparameter tuning - single process

### ISSUE THREAD

**Issue by NicolasHaeffner** [DLR-RM/rl-baselines3-zoo#66]
Hi everyone.

I am trying to do hyperparameter tuning for a custom environment of mine. 
The problem is, that I cannot run multiple processes of the same environment, since it loads a dll with ctypes, that will only let me run one instance at a time. 
Does anybody see any workaround for that? 

Thanks in advance

**Comment by Miffyli** [comment]
I will let @araffin provide answers for this one, but I highly recommend fixing the limitation in your environment. Being able to run RL experiments/optimization in parallel is a must for doing proper results in reasonable time, unless your environment is very fast (above 10000 steps-per-second).

**Comment by NicolasHaeffner** [comment]
Thanks for your quick response. 
That's what I suspected (feared). 
I am trying to come up with something clever, but the simulation software I use is giving me a hard time - on that note: it is not very fast either.. more like 100 steps per second

**Comment by araffin** [comment]
> Does anybody see any workaround for that?

What about distributed hyperparameter optimization?

See [Readme](https://github.com/DLR-RM/rl-baselines3-zoo#hyperparameter-tuning) and [Optuna](https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/004_distributed.html) documentation.

**Comment by NicolasHaeffner** [comment]
Unfortunately, that's not really an option either, due to licensing limitations. 
I am using [this](https://www.carsim.com/). 
I can train the agent on one environment no problem, but as it tries to spawn more environments it breaks.

**Comment by Miffyli** [comment]
There is no other workaround for this sadly :(. You _could_ run the hyperparameter optimization with one environment alone but this will take a very long time.

**Comment by NicolasHaeffner** [comment]
I have spent some more time trying to get the environment to parallelize and I've had some minor successes, so that I think it might be possible somehow. (The error messages bikesim is giving me are not really descriptive...) 
Thank you both for your inputs, I really appreciate!
