### ISSUE TITLE
Colab rl-baselines-zoo Error while finding module specification for 'train.py'

### ISSUE THREAD

**Issue by lorepieri8** [DLR-RM/rl-baselines3-zoo#70]
**Describe the bug**
`/usr/bin/python3: Error while finding module specification for 'train.py' (ModuleNotFoundError: __path__ attribute not found on 'train' while trying to find 'train.py')
`

**Code example**
Run the cell `!python -m train.py --algo ppo --env MountainCar-v0 -n 50000 -optimize --n-trials 1000 --n-jobs 2 --sampler tpe --pruner median`
in [https://colab.research.google.com/github/Stable-Baselines-Team/rl-colab-notebooks/blob/sb3/rl-baselines-zoo.ipynb](url)

**Comment by araffin** [comment]
Hello,
thanks for reporting the issue. Just remove the "-m" and it should work ;)

**Comment by lorepieri8** [comment]
Yep, working now.

**Comment by araffin** [comment]
now fixed ;) (I pushed the new version)
