### ISSUE TITLE
Support recording videos for best model and checkpoints [feature request] 

### ISSUE THREAD

**Issue by mcres** [DLR-RM/rl-baselines3-zoo#73]
Currently, the `utils/record_video.py` module loads the latest model by default, but there are no options for loading the possible best model or checkpoints saved during training.

**Comment by mcres** [comment]
I have a PR ready. Should I point to `master` or wait for an admin to create a specific branch, e.g. `feat/record-checkpoints`?

**Comment by araffin** [comment]
Hello,
Please create a PR that points to master ;)
