### ISSUE TITLE
Record a training experiment [feature request]

### ISSUE THREAD

**Issue by mcres** [DLR-RM/rl-baselines3-zoo#75]
I think it would be useful to create a video of a specific training experiment, as long as the training saved one or more checkpoints.
The final result would be a video where each checkpoint is loaded and executed, and the format could be specified, e.g. `mp4` or `gif`. The process would be like this:

- Record a video of each checkpoint and final models (perhaps best model also if available) into a temporary directory, using `utils/record_video.py`.
-  Use `ffmpeg` or another tool to join the videos together and convert it into other formats. Wait some time between the different checkpoints, so the final video isn't too fast and confusing.
- It would be nice if the number of checkpoint appeared as text in the video, and changed with the models recorded accordingly.

The problems I can think ahead for implementing this:
- In order to keep the code clean, I'd suggest implementing this feature in `utils/record_training.py`. However, I'm not sure if it's  a good idea to call the module `utils/record_video.py` within this new file.
- For me, it would make more sense to specify a video length by the number of episodes rather than the number of steps, so when _x_ episodes are done, the video would stop. If that's the case, [VecVideoRecorder](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/vec_env/vec_video_recorder.py) would need to be modified.

**Comment by araffin** [comment]
Holà,

I've got mixed feelings about that (I would probably need to test it to see if it is really useful or not) as it seems more like a wrapper around ffmpeg.
So, if you do such script, I would happy to test it (you could open a draft PR) but I'm not sure if it will be merged at the end.

>However, I'm not sure if it's a good idea to call the module utils/record_video.py within this new file.

That's not a problem, and that's how I would do it to avoid code duplication (the same way benchmark script is calling `enjoy.py` under the hood).

>For me, it would make more sense to specify a video length by the number of episodes rather than the number of steps, so when x episodes are done, the video would stop. If that's the case, VecVideoRecorder would need to be modified.

unfortunately, some environments have no timeout, which means that an episode can have an infinite number of steps (this happens with atari games when using a deterministic controller). For env with a fixed number of steps, there is a one to one correspondence between episodes and number of steps. 
Also, when using steps, you know in advance how long will you video be (and change the fps too).

What we could do however is allow to pass a maximum number of episodes, and the good news is that we only need to change that line: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/utils/record_video.py#L94

(We need to check what happen if `VecVideoRecorder` is stopped before the maximum number of steps).

**Comment by mcres** [comment]
> I've got mixed feelings about that (I would probably need to test it to see if it is really useful or not) as it seems more like a wrapper around ffmpeg.

I mentioned `ffmpeg`, but it could be another tool like `moviepy`. I'm happy to hear suggestions if you have any.
Apart from that and see if it's useful, is there anything else that can make you skeptical? :-)

> unfortunately, some environments have no timeout, which means that an episode can have an infinite number of steps (this happens with atari games when using a deterministic controller). For env with a fixed number of steps, there is a one to one correspondence between episodes and number of steps.
Also, when using steps, you know in advance how long will you video be (and change the fps too).

Yep, totally right, I didn't think about that.

**Comment by araffin** [comment]
>I mentioned ffmpeg, but it could be another tool like moviepy. I'm happy to hear suggestions if you have any.
Apart from that and see if it's useful, is there anything else that can make you skeptical?

ffmpeg is not really an issue (it is required to use the record video anyway), it's more how often would people use that feature and if it is a useful one.

**Comment by mcres** [comment]
I'll assign myself, since I've already done some work.
