### ISSUE TITLE
[Question] --n-jobs>1 workaround>

### ISSUE THREAD

**Issue by justinkterry** [DLR-RM/rl-baselines3-zoo#79]
Hey, I'm working on creating a fork of this to create various tuned baselines for PettingZoo environments, and I've been running some initial experiments. Everything has worked as expected except one thing. Here's the command I've been testing with:

`python3 train.py --algo ppo --env LunarLanderContinuous-v2 -n 2000000 -optimize --n-trials 1000 --n-jobs 2 --sampler tpe --pruner median --study-name lunar_lander_1 --storage mysql://[redacted]`

I'm running this on a machine with 2 GPUs. However, only 1 job starts (despite --n-jobs=1). Do you guys just specify each job with `CUDA_VISIBLE_DEVICES=1` or whatever and start a job for every single GPU, or is there something smarter that I can't find on Google?

(Also sorry for accidentally posting my last issue on the old repo)

**Comment by araffin** [comment]
Hello,

>However, only 1 job starts (despite --n-jobs=1).

I think this is more a optuna related issue. `n_jobs` refers to the number of workers in parallel for one process and was in fact deprecated in the latest release: https://github.com/optuna/optuna/releases/tag/v2.7.0

what you should do instead is start several process that point to the same study (cf. optuna doc).

**Comment by justinkterry** [comment]
Thanks a ton for confirming.

One last question--in the readme you show using 1000 trials to find optimal hyperparameters. Is 1000 actually how many trials you've been using for tuning, or was it put in the readme for a different reason?

**Comment by araffin** [comment]
>One last question--in the readme you show using 1000 trials to find optimal hyperparameters. Is 1000 actually how many trials you've been using for tuning, or was it put in the readme for a different reason?

1000 is just an example budget, it is the maximal number of trials you want to do. In practice,, depending on your problem of course, you usually need less trials to find good hyperparameters (and at some point, most of them will be pruned).

**Comment by justinkterry** [comment]
Thanks!

**Comment by kingjin94** [comment]
For anyone wondering: It seems this problem has been solved completely with the usage of MaxTrialsCallback (https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.MaxTrialsCallback.html#optuna-study-maxtrialscallback) within exp_manager and the `--max-total-trials` train.py parameter.
