### ISSUE TITLE
[Question] Every few days all rl-zoo jobs on a node stop without any errors and I can't figure out why

### ISSUE THREAD

**Issue by jkterry1** [DLR-RM/rl-baselines3-zoo#81]
In my trials tuning both pettingzoo gym environments, all optuna jobs on one node have just simply stopped twice now. There have been no system errors, nothing printed to stdout, the processes have all stopped (no zombie processes etc.), and the jobs have been very far from finishing and can simply be restarted by connecting them to the sql server again seemingly without issue. They just sort of magically stop and I have no idea why. Have you seen anything like this before?

**Comment by araffin** [comment]
Hello,
I supposed you are using a cluster?
Make sure you did not use more cluster resources (RAM, time, ...) that you asked for...

**Comment by justinkterry** [comment]
I already checked that (audio it would generate an error to stdout)

**Comment by schuderer** [comment]
If it stops without any trace, I think it might be killed by the kernel. The linux kernel usually only does this for severe reasons, like running out of RAM or system volume space, like Antonin mentioned. There might be more info in `/var/log/kern.log` ([related StackExchange question](https://stackoverflow.com/questions/726690/what-killed-my-process-and-why)).
