### ISSUE TITLE
[Minor Bug] Unnecessary and mildy confusing print statement during hyperparameter optimization

### ISSUE THREAD

**Issue by justinkterry** [DLR-RM/rl-baselines3-zoo#87]
Starting a hyperparameter run with train.py prints out something like this:

```
========== LunarLanderContinuous-v2 ==========
Seed: 3139539977
OrderedDict([('batch_size', 64),
             ('ent_coef', 0.01),
             ('gae_lambda', 0.98),
             ('gamma', 0.999),
             ('n_envs', 16),
             ('n_epochs', 4),
             ('n_steps', 1024),
             ('n_timesteps', 1000000.0),
             ('policy', 'MlpPolicy')])
Using 4 environments
Overwriting n_timesteps with n=4000000
```

The problem is that the OrderedDict that's printed is the parameters for the environment in the relevant .yml file. It has no impact on hyperparameter tuning, isn't even used, can make it look like you're doing something wrong (e.g. by default you're tuning hyperparameters that aren't included in that list) and the origin of it takes a shockingly long time to hunt down to confirm you aren't somehow doing something wrong.

**Comment by araffin** [comment]
>It has no impact on hyperparameter tuning, isn't even used,

It does, all the hyperparameters that are not part of the hyperparameter search will default to the one from the yaml file.

**Comment by araffin** [comment]
>How would you feel about a message clarifying where the ordered dict is from then?

What do you mean exactly? (my answer will be most probably yes but I just want to be sure ;))

**Comment by justinkterry** [comment]
(sorry for the delayed reply)

I meant a message like "Default hyperparameters for environment (ones being tuned will be overridden)""

**Comment by araffin** [comment]
>I meant a message like "Default hyperparameters for environment (ones being tuned will be overridden)""

sounds good ;) (my upvote did not create a notification ...)
