### ISSUE TITLE
Training from scratch take too much time (in Atari envs for 10M steps) [question]

### ISSUE THREAD

**Issue by Eunice330** [DLR-RM/rl-baselines3-zoo#95]
**Describe the bug**
When I tried training dqn from scratch in Atari envs for 10M steps, it only takes about 1000MiB on my gpu and it's really slow (I have to wait for more than 2 days for it to complete). In other pytorch dqn implementations it would take much less time, but would take much larger space on the gpu (~ 10000MiB). However I really like the structure here and the trained agents provided in this repo. So is there any help on how to speed it up? Thanks so much!!

**System Info**
Describe the characteristic of your environment:
 * Describe how Stable Baselines3 was installed: pip
 * GPU models and configuration: NVIDIA GeForce RTX-2080Ti, CUDA 10.1
 * Python version: 3.7.10
 * PyTorch version: 1.6.0+cu101

**Comment by araffin** [comment]
Hello,

Please provide the command line you are using.

>and it's really slow (I have to wait for more than 2 days for it to complete). I

I guess you have the evaluation activated, you can probably increase the speed by deactivating it `--eval-freq -1`.

An upcoming feature should also make the learning much faster: https://github.com/DLR-RM/stable-baselines3/issues/179

**Comment by Eunice330** [comment]
Thanks for the reply! The current eval-freq is 1M. I'll try deactivating it.
