### ISSUE TITLE
[Question] Why aren't environments normalized by default?

### ISSUE THREAD

**Issue by justinkterry** [DLR-RM/rl-baselines3-zoo#96]
As best I can tell after going through for an hour and adding a print statement, environments aren't normalized by default. Why is this desirable behavior for creating baselines?

**Comment by araffin** [comment]
>As best I can tell after going through for an hour and adding a print statement, environments aren't normalized by default. Why is this desirable behavior for creating baselines?

Why would you use normalization if it is not needed? And would you use obs and reward normalization?
Also, in some cases (image obs), `VecNormalize` is not applicable.

**Comment by justinkterry** [comment]
Sorry for the delayed reply. I believe that normalization should be turned on by default because it's a general best practice, these are intended to be baselines, and to the best of my knowledge at least it can't hurt anything when done correctly. The components of VecNormalize not applicable to be specific environments could be turned off automatically or via tests.

**Comment by araffin** [comment]
>I believe that normalization should be turned on by default because it's a general best practice, these are intended to be baselines

Baselines are meant to reproduce results on known environments. And normalization (including reward normalization) does not always help.

You should also avoid doing double normalization (if the user already normalizes the data, we should not normalize it again).
